### ISSUE TITLE
Problem with proxy address in prebuilt image. EG apt-get update does not run in container. With workaround.

### ISSUE THREAD

**Issue by JohnnyC1951** [bigbluebutton/docker#1]
Line 4 of the docker file has the proxy IP set to 192.168.0.130 and so the container cannot reach the internet. The docs say that, by default, this is commented out, but it is not. IE:
`RUN echo 'Acquire::http::Proxy "http://192.168.0.130:3142";'  > /etc/apt/apt.conf.d/01proxy`
Should be:
`# RUN echo 'Acquire::http::Proxy "http://192.168.0.130:3142";'  > /etc/apt/apt.conf.d/01proxy`
The pre-built distribution image needs rebuilding ;)
or rebuild it yourself.
I just did a rebuild, after commenting out that line, and it now works :)

**Comment by joshua-arts** [comment]
Hey @JohnnyC1951,

Thanks for pointing this out, was an oversight on our end. I just added a commit to master (0f322af) which fixes it, and I'll be updating the image on Dockerhub shortly!
