### ISSUE TITLE
Invalid interpolation

### ISSUE THREAD

**Issue by leon1995** [bigbluebutton/docker#100]
Hi,

when I want to start the docker compose file I get the following error: 
```
ERROR: Invalid interpolation format for "environment" option in service "bbb-web": "${DEV_MODE:-}"
```

what have I done wrong?

**Comment by alangecker** [comment]
most likely you use an outdated docker-compose version ;)

```
$ docker-compose --version                                                                                      
docker-compose version 1.29.1, build unknown
```

Use this guide for installing the latest version:
https://docs.docker.com/compose/install/

**Comment by leon1995** [comment]
Thanks for you quick answer. that solved my problem!
