### ISSUE TITLE
presentation doesnt working "connection refuse"

### ISSUE THREAD

**Issue by iscandar** [bigbluebutton/docker#106]
hi guys im alejandro 
I just started using this really cool script, but I have a problem, in https mode the html5 docker registers this problem

```
 bbb-html5                                            "/entrypoint.sh" 

error: No file found. Error: connect ECONNREFUSED 127.0.1.1:443
error: Error parsing image size. Error: connect ECONNREFUSED 127.0.1.1:443
```

with this problem i can't see the default presentation.
however, the default presentation can be reached from the outside, even the loaded pdfs, but they are never displayed. could you help me please ??

**Comment by iscandar** [comment]
problem with configuration host in vps

**Comment by qroac** [comment]
Well, do you by chance remember what the configuration problem was?

I encounter the very same error with default presentation and after uploading any other presentation.
So I cannot present anything.
