### ISSUE TITLE
Change Salt

### ISSUE THREAD

**Issue by Alferez** [bigbluebutton/docker#11]
I see in documentation of setup.sh file that it's posible set Secret Salt, but in code no see where set this Salt, only get store Salt for use it:

<pre>
# Ensure bbb-apps-akka has the latest shared secret from bbb-web
SECRET=$(cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties | grep -v '#' | grep securitySalt | cut -d= -f2);
</pre>

I try to use the -s parameter to configure Salt, but I can not get it

<pre>
# Ensure bbb-apps-akka has the latest shared secret from bbb-web
if [ -z $SECRET ]
then
	SECRET=$(cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties | grep -v '#' | grep securitySalt | cut -d= -f2);
else
	sed -i "s/securitySalt=.*/securitySalt=$SECRET/" /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
fi

sed -i "s/String salt =.*/String salt = \"$SECRET\";/"  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp

sed -i "s/sharedSecret[ ]*=[ ]*\"[^\"]*\"/sharedSecret=\"$SECRET\"/g"   /usr/share/bbb-apps-akka/conf/application.conf
</pre>

I try in setup.sh use bbb-conf --setsalt but does not work.

**Comment by ffdixon** [comment]
Can you try

~~~
  sudo bbb-conf --setsecret <secret>
~~~

**Comment by Alferez** [comment]
Yes, i try setsecret but y try change in setup.sh script and no later into runing docker.

In setup.sh you can see:
<pre>
# In a standard BigBlueButton server you would use `bbb-conf --setip IP` to configure it listen to a given IP, but
# we are using supervisorctl (not systemd) in, so we apply all the configuration changes before running supervisorctl at
# the end of this script
</pre>

If you try use bbb-conf in setup give error because system no are up.

**Comment by ffdixon** [comment]
I understand now what you are saying as we're not using the `SECRET` value when setting up the docker container.   

We need to add some more logic here https://github.com/bigbluebutton/docker/blob/master/setup.sh#L209 to use the `SECRET` if given on the command line.

Thanks for pointing this out.

**Comment by ffdixon** [comment]
Added logic to set the shared secret from `-s` command to run the docker container.  Can you try rebuilding the docker container and let us know if this works now.
