### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by tienthanh2509** [bigbluebutton/docker#12]
Use the below command to run bigbluebutton
```bash
 docker run --rm \
> -p 80:80 \
> -p 443:443 \
> -p 1935:1935 \
> -p 5066:5066 \
> -p 3478:3478 \
> -p 3478:3478/udp \
> bigbluebutton/bigbluebutton -h 172.16.212.51
```

But docker entrypoint throw an error

`/root/setup.sh: line 228: updatedb: command not found`

```
+ getopts eh: opt
+ case $opt in
+ HOST=172.16.212.51
+ getopts eh: opt
+ apt-get install -y bbb-demo
Reading package lists...
Building dependency tree...
Reading state information...
bbb-demo is already the newest version (1:2.0.0-14).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ /etc/init.d/tomcat7 start
 * Starting Tomcat servlet engine tomcat7
   ...done.
+ '[' '!' -f /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp ']'
+ sudo /etc/init.d/tomcat7 stop
 * Stopping Tomcat servlet engine tomcat7
   ...done.
+ PROTOCOL_HTTP=http
+ PROTOCOL_RTMP=rtmp
++ head -n1
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep addr:
+++ grep '^et.*'
+++ sed 's/.*addr://g'
+++ head -n1
+++ sed 's/ .*//g'
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep addr:
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
+++ grep '^en.*'
++ echo 172.17.0.2
+ IP=172.17.0.2
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "external_rtp_ip=")]/@data' --value stun:coturn /opt/freeswitch/conf/vars.xml
/root/setup.sh: line 74: xmlstarlet: command not found
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "external_sip_ip=")]/@data' --value stun:coturn /opt/freeswitch/conf/vars.xml
/root/setup.sh: line 75: xmlstarlet: command not found
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "local_ip_v4=")]/@data' --value 172.17.0.2 /opt/freeswitch/conf/vars.xml
/root/setup.sh: line 76: xmlstarlet: command not found
+ sed -i 's/proxy_pass .*/proxy_pass http:\/\/172.17.0.2:5066;/g' /etc/bigbluebutton/nginx/sip.nginx
+ sed -i 's/http[s]*:\/\/\([^"\/]*\)\(["\/]\)/http:\/\/172.16.212.51\2/g' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/rtmp[s]*:\/\/\([^"\/]*\)\(["\/]\)/rtmp:\/\/172.16.212.51\2/g' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/server_name  .*/server_name  172.16.212.51;/g' /etc/nginx/sites-available/bigbluebutton
+ sed -i 's/bigbluebutton.web.serverURL=http[s]*:\/\/.*/bigbluebutton.web.serverURL=http:\/\/172.16.212.51/g' /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties streamBaseUrl rtmp://172.16.212.51/screenshare
+ sed -i 's<^[[:blank:]#]*\(streamBaseUrl\).*<\1=rtmp://172.16.212.51/screenshare<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpUrl http://172.16.212.51/screenshare
+ sed -i 's<^[[:blank:]#]*\(jnlpUrl\).*<\1=http://172.16.212.51/screenshare<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpFile http://172.16.212.51/screenshare/screenshare.jnlp
+ sed -i 's<^[[:blank:]#]*\(jnlpFile\).*<\1=http://172.16.212.51/screenshare/screenshare.jnlp<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
+ change_var_value /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties bbb.sip.app.ip 172.17.0.2
+ sed -i 's<^[[:blank:]#]*\(bbb.sip.app.ip\).*<\1=172.17.0.2<' /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
+ change_var_value /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties freeswitch.ip 172.17.0.2
+ sed -i 's<^[[:blank:]#]*\(freeswitch.ip\).*<\1=172.17.0.2<' /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
+ sed -i 's/bbbWebAPI[ ]*=[ ]*"[^"]*"/bbbWebAPI="http:\/\/172.16.212.51\/bigbluebutton\/api"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/bbbWebHost[ ]*=[ ]*"[^"]*"/bbbWebHost="172.16.212.51"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/deskshareip[ ]*=[ ]*"[^"]*"/deskshareip="172.16.212.51"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/defaultPresentationURL[ ]*=[ ]*"[^"]*"/defaultPresentationURL="http:\/\/172.16.212.51\/default.pdf"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ cat
++ openssl rand -hex 16
+ TURN_SECRET=9e8b3de035cb81dad90cc2bad324434d
+ cat
+ cat
+ cat
++ cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
++ grep -v '#'
++ grep securitySalt
++ cut -d= -f2
+ SECRET=6bbdc14d32df911075a5f3176adc1a0f
+ sed -i 's/sharedSecret[ ]*=[ ]*"[^"]*"/sharedSecret="6bbdc14d32df911075a5f3176adc1a0f"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/BigBlueButtonURL = "http[s]*:\/\/\([^"\/]*\)\(["\/]\)/BigBlueButtonURL = "http:\/\/172.16.212.51\2/g' /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
+ sed -i 's/playback_host: .*/playback_host: 172.16.212.51/g' /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
+ sed -i 's/daemonize no/daemonize yes/g' /etc/redis/redis.conf
+ sed -i 's|"wsUrl.*|"wsUrl": "ws://172.16.212.51/bbb-webrtc-sfu",|g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings-production.json
+ rm /usr/share/red5/log/sip.log
rm: cannot remove '/usr/share/red5/log/sip.log': No such file or directory
+ sed -i 's/BigBlueButton.logger.debug("rap-archive-worker done")/sleep 20; BigBlueButton.logger.debug("rap-archive-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-process-worker done")/sleep 20; BigBlueButton.logger.debug("rap-process-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-sanity-worker done")/sleep 20 ; BigBlueButton.logger.debug("rap-sanity-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-publish-worker done")/sleep 20; BigBlueButton.logger.debug("rap-publish-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb
+ export NODE_ENV=production
+ NODE_ENV=production
+ export DAEMON_LOG=/var/log/kurento-media-server
+ DAEMON_LOG=/var/log/kurento-media-server
+ export 'GST_DEBUG=3,Kurento*:4,kms*:4'
+ GST_DEBUG='3,Kurento*:4,kms*:4'
+ export KURENTO_LOGS_PATH=/var/log/kurento-media-server
+ KURENTO_LOGS_PATH=/var/log/kurento-media-server
+ cat

BigBlueButton is now starting up at this address

  http://172.16.212.51

+ updatedb
/root/setup.sh: line 228: updatedb: command not found
+ exec /usr/bin/supervisord
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '

```

Please check

**Comment by ffdixon** [comment]
We can see there are other errors

~~~
  xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "external_rtp_ip=")]/@data' --value stun:coturn /opt/freeswitch/conf/vars.xml
/root/setup.sh: line 74: xmlstarlet: command not found
~~~

Can you try building the docker container from source, see the steps at https://github.com/bigbluebutton/docker in the README.me and let us know if that works.

**Comment by tienthanh2509** [comment]
It's worked 👍 

Thanks

**Comment by VincentSC** [comment]
When building from scratch, it is `/bin/systemd,--system,--unit=multi-user.target` instead of `/root/setup.sh`. Besides that the file has moved to `/opt/bbb-docker`, it looks like dockerhub needs a big update.

**Comment by cypriotxx** [comment]
hi there, anyone could help with this please ? thank you and hope you are all well

# docker run --rm -p 8448:80/tcp -p 1935:1935 -p 3478:3478 -p 3478:3478/udp bigbluebutton/bigbluebutton           :latest -h 192.168.1.130
+ getopts eh: opt
+ case $opt in
+ HOST=192.168.1.130
+ getopts eh: opt
+ apt-get install -y bbb-demo
Reading package lists...
Building dependency tree...
Reading state information...
bbb-demo is already the newest version (1:2.0.0-14).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ /etc/init.d/tomcat7 start
 * Starting Tomcat servlet engine tomcat7
   ...done.
+ '[' '!' -f /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp ']'
+ sudo /etc/init.d/tomcat7 stop
 * Stopping Tomcat servlet engine tomcat7
   ...done.
+ PROTOCOL_HTTP=http
+ PROTOCOL_RTMP=rtmp
++ head -n1
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep addr:
+++ grep '^et.*'
+++ sed 's/ .*//g'
+++ head -n1
+++ sed 's/.*addr://g'
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep addr:
+++ grep '^en.*'
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
++ echo 10.0.3.3
+ IP=10.0.3.3
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "external_rtp_ip=")]/@data' --value stun:coturn /opt/f           reeswitch/conf/vars.xml
/root/setup.sh: line 74: xmlstarlet: command not found
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "external_sip_ip=")]/@data' --value stun:coturn /opt/f           reeswitch/conf/vars.xml
/root/setup.sh: line 75: xmlstarlet: command not found
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "local_ip_v4=")]/@data' --value 10.0.3.3 /opt/freeswit           ch/conf/vars.xml
/root/setup.sh: line 76: xmlstarlet: command not found
+ sed -i 's/proxy_pass .*/proxy_pass http:\/\/10.0.3.3:5066;/g' /etc/bigbluebutton/nginx/sip.nginx
+ sed -i 's/http[s]*:\/\/\([^"\/]*\)\(["\/]\)/http:\/\/192.168.1.130\2/g' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/rtmp[s]*:\/\/\([^"\/]*\)\(["\/]\)/rtmp:\/\/192.168.1.130\2/g' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/server_name  .*/server_name  192.168.1.130;/g' /etc/nginx/sites-available/bigbluebutton
+ sed -i 's/bigbluebutton.web.serverURL=http[s]*:\/\/.*/bigbluebutton.web.serverURL=http:\/\/192.168.1.130/g' /var/lib/tomcat7/webapps/bigblue           button/WEB-INF/classes/bigbluebutton.properties
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties streamBaseUrl rtmp://192.168.1.130/screenshare
+ sed -i 's<^[[:blank:]#]*\(streamBaseUrl\).*<\1=rtmp://192.168.1.130/screenshare<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.pr           operties
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpUrl http://192.168.1.130/screenshare
+ sed -i 's<^[[:blank:]#]*\(jnlpUrl\).*<\1=http://192.168.1.130/screenshare<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properti           es
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpFile http://192.168.1.130/screenshare/screenshare.jn           lp
+ sed -i 's<^[[:blank:]#]*\(jnlpFile\).*<\1=http://192.168.1.130/screenshare/screenshare.jnlp<' /usr/share/red5/webapps/screenshare/WEB-INF/sc           reenshare.properties
+ change_var_value /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties bbb.sip.app.ip 10.0.3.3
+ sed -i 's<^[[:blank:]#]*\(bbb.sip.app.ip\).*<\1=10.0.3.3<' /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
+ change_var_value /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties freeswitch.ip 10.0.3.3
+ sed -i 's<^[[:blank:]#]*\(freeswitch.ip\).*<\1=10.0.3.3<' /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
+ sed -i 's/bbbWebAPI[ ]*=[ ]*"[^"]*"/bbbWebAPI="http:\/\/192.168.1.130\/bigbluebutton\/api"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/bbbWebHost[ ]*=[ ]*"[^"]*"/bbbWebHost="192.168.1.130"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/deskshareip[ ]*=[ ]*"[^"]*"/deskshareip="192.168.1.130"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/defaultPresentationURL[ ]*=[ ]*"[^"]*"/defaultPresentationURL="http:\/\/192.168.1.130\/default.pdf"/g' /usr/share/bbb-apps-akka/co           nf/application.conf
+ cat
++ openssl rand -hex 16
+ TURN_SECRET=3b1844426a31ddfc381d2b0e3ab807d3
+ cat
+ cat
+ cat
++ cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
++ grep -v '#'
++ grep securitySalt
++ cut -d= -f2
+ SECRET=6bbdc14d32df911075a5f3176adc1a0f
+ sed -i 's/sharedSecret[ ]*=[ ]*"[^"]*"/sharedSecret="6bbdc14d32df911075a5f3176adc1a0f"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/BigBlueButtonURL = "http[s]*:\/\/\([^"\/]*\)\(["\/]\)/BigBlueButtonURL = "http:\/\/192.168.1.130\2/g' /var/lib/tomcat7/webapps/dem           o/bbb_api_conf.jsp
+ sed -i 's/playback_host: .*/playback_host: 192.168.1.130/g' /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
+ sed -i 's/daemonize no/daemonize yes/g' /etc/redis/redis.conf
+ sed -i 's|"wsUrl.*|"wsUrl": "ws://192.168.1.130/bbb-webrtc-sfu",|g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings-prod           uction.json
+ rm /usr/share/red5/log/sip.log
rm: cannot remove '/usr/share/red5/log/sip.log': No such file or directory
+ sed -i 's/BigBlueButton.logger.debug("rap-archive-worker done")/sleep 20; BigBlueButton.logger.debug("rap-archive-worker done")/g' /usr/loca           l/bigbluebutton/core/scripts/rap-archive-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-process-worker done")/sleep 20; BigBlueButton.logger.debug("rap-process-worker done")/g' /usr/loca           l/bigbluebutton/core/scripts/rap-process-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-sanity-worker done")/sleep 20 ; BigBlueButton.logger.debug("rap-sanity-worker done")/g' /usr/local           /bigbluebutton/core/scripts/rap-sanity-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-publish-worker done")/sleep 20; BigBlueButton.logger.debug("rap-publish-worker done")/g' /usr/loca           l/bigbluebutton/core/scripts/rap-publish-worker.rb
+ export NODE_ENV=production
+ NODE_ENV=production
+ export DAEMON_LOG=/var/log/kurento-media-server
+ DAEMON_LOG=/var/log/kurento-media-server
+ export 'GST_DEBUG=3,Kurento*:4,kms*:4'
+ GST_DEBUG='3,Kurento*:4,kms*:4'
+ export KURENTO_LOGS_PATH=/var/log/kurento-media-server
+ KURENTO_LOGS_PATH=/var/log/kurento-media-server
+ cat

BigBlueButton is now starting up at this address

  http://192.168.1.130

+ updatedb
/root/setup.sh: line 228: updatedb: command not found
+ exec /usr/bin/supervisord
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configurat           ion file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute p           ath to a configuration file for improved security.
  'Supervisord is running as root and it is searching '

**Comment by diwoMonsoon** [comment]
> hen building from scratch, it is `/bi`

This error still exists I pulled the image and ran on mac
