### ISSUE TITLE
How to get BIGBLUEBUTTON_SECRET in docker container?

### ISSUE THREAD

**Issue by thomasfeng61** [bigbluebutton/docker#122]
I am a new docker learner. Please give me some suggestion. Thanks a lot.

**Comment by bhuvankrishna** [comment]
@thomasfeng61 did you find a solution for it? If you have can you share the steps to get the secret from docker?

**Comment by thomasfeng61** [comment]
If you have installed Bigbluebutton on docker using bbb-docker be the folder name. Then you can use the way below:

cd /bbb-docker
nano .nev

# search "SHARED_SECRET" and  you will find "Secret key"
