### ISSUE TITLE
Upgrade to current version (2.3.2)

### ISSUE THREAD

**Issue by ikarelin** [bigbluebutton/docker#124]
Hello guys.
How can I upgrade my docker containers to the current release of BBB, which is now 2.3.2 ?

**Comment by joergmschulz** [comment]
scripts/upgrade ?

**Comment by veixus** [comment]
There was a mention here

https://github.com/bigbluebutton/docker/blob/develop/docs/upgrading.md

**Comment by joergmschulz** [comment]
Had a deeper look - currently all is fixed to the 2.3.0 version. But whenever PR #120 is implemented you're free to upgrade/change version. When you look at the contents of the PR, you'll see it's not trivial.

**Comment by ikarelin** [comment]
> Had a deeper look - currently all is fixed to the 2.3.0 version. But whenever PR #120 is implemented you're free to upgrade/change version. When you look at the contents of the PR, you'll see it's not trivial.

Yep, I've made changes from PR #120, now building. Have you tested it with version 2.3.2 or is it better to use version 2.3.0 from the main repository on production servers ?

**Comment by doodlemania2** [comment]
@ikarelin - meaning you merged the PR or you just applied it to a fork you are running?

**Comment by ikarelin** [comment]
Guess, I'm giving up. Big Blue Button is not for me. I've spent about a week trying to run it with docker and with the current version. Thank for your help though.

**Comment by ikarelin** [comment]
Invalid BigBlueButton Endpoint and Secret - it's a most common error when trying to upgrade or build it.

**Comment by ikarelin** [comment]
Another stupid error is Big Blue Button constantly loosing video, coturn is working though.
