### ISSUE TITLE
ssl certificate integration

### ISSUE THREAD

**Issue by it-toppp** [bigbluebutton/docker#13]
Can this container be used together traefik for proper operation ssl?
bigbluebutton:
    container_name: bigbluebutton
    hostname: bigbluebutton
    image: bigbluebutton/bigbluebutton
    ports:
     - 81:80/tcp
     - 1935:1935/tcp
     - 5066:5066/tcp
     - 3478:3478/tcp
     - 32730-32768:32730-32768/udp
     - 2202:2202
    environment:
     - HOST=serversupport.pp.ua
    cap_add:
     - NET_ADMIN
    labels:
      - "traefik.enable=true"
      - "traefik.q.frontend.rule=Host:______; PathPrefixStrip:/ "
      - "traefik.q.port=80"
      - "traefik.a.frontend.rule=Host:_______:7443; "
      - "traefik.a.port=5066"
      - "traefik.protocol=http"

  traefik:
    # https://hub.docker.com/_/traefik/
    image: traefik:latest
    command: --api --docker --acme.email="admin@_____-"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access to Docker
      - ./traefik.toml:/traefik.toml              # Traefik configuration
      - ./acme.json:/acme.json                    # SSL certificates
    ports:
      # Map port 80 and 443 on the host to this container.
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.protocol=http"

**Comment by satyaakam** [comment]
according to https://docs.traefik.io/ its a reverse proxy and load balancer , you would still be  using docker to  run bbb

**Comment by Aoleara** [comment]
Denunciados, segid, seguid

**Comment by Aoleara** [comment]
> Denunciados, segid,violacion, acoso, amenazas, incitación al suicidio... Bestias nauseabundas cobardesseguid

**Comment by Aoleara** [comment]
> Denunciados, segid,violacion, acoso, amenazas, incitación al suicidio... Bestias nauseabundas cobardesseguid

**Comment by satyaakam** [comment]
@it-toppp hope you are still working in this , you can try this load balancer  https://github.com/blindsidenetworks/scalelite

**Comment by cljk** [comment]
> according to https://docs.traefik.io/ its a reverse proxy and load balancer , you would still be using docker to run bbb , i hope your are not trying to run bbb docker in production environment , it is for testing purposes only , the easiest way to install bbb is use the install script https://github.com/bigbluebutton/bbb-install

Sad, that the docker-image is not meant for production use - since we´re running most newly introduced services inside a container.

**Comment by alangecker** [comment]
@cljk maybe have a look into this fork :)
https://github.com/alangecker/bigbluebutton-docker
I know quite a lot of instances running this stable in production

**Comment by cljk** [comment]
> @cljk maybe have a look into this fork :)
> https://github.com/alangecker/bigbluebutton-docker
> I know quite a lot of instances running this stable in production

Thank you!
Looks promising..

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
