### ISSUE TITLE
java.lang.NullPointerException 500

### ISSUE THREAD

**Issue by AnatoliChe** [bigbluebutton/docker#14]
Hi!
When I start docker with ip address everything is ok.

But if I try to start like docker run [skip] -h bbb.realdomname.com
I have 

Status Code | 500
-- | --
Exception Type | null
Message | null
Exception | java.lang.NullPointerException 	at org.apache.jsp.demo1_jsp.getJoinURLExtended(demo1_jsp.java:259) 	at org.apache.jsp.demo1_jsp.getJoinURL(demo1_jsp.java:182) 	at org.apache.jsp.demo1_jsp._jspService(demo1_jsp.java:1241) 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439) 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:400) 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:344) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436) 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078) 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 	at java.lang.Thread.run(Thread.java:748)

I can see this problem at once as I change ip to hostname in /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
or 
219 sed -i "s/BigBlueButtonURL = \"http[s]*:\/\/\([^\"\/]*\)\([\"\/]\)/BigBlueButtonURL = \"$PROTOCOL_HTTP:\/\/$HOST\2/g" \
220   /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
in setup.sh

**Comment by ffdixon** [comment]
Thanks for pointing this out -- we'll take a closer look.

**Comment by AnatoliChe** [comment]
I found problem.
It was related with DNS name in test environment. System inside docker did not know ip of test host name.
So it was solved with /etc/hosts.
On the production system I do not have this issue.
Thanks.

**Comment by moqmar** [comment]
For someone with the same issue behind a TLS-terminating reverse proxy: set "HTTP_PROTOCOL" to "https" in setup.sh :)
