### ISSUE TITLE
Setup fails on absolute certificate path

### ISSUE THREAD

**Issue by gempa-stephan** [bigbluebutton/docker#157]
The following sed line fails if the https proxy feature is deactivated and an absolute certificate or private key file path is specified:

https://github.com/bigbluebutton/docker/blob/0dd3d9a0bc7ea3169e71f27246702f870a3607db/scripts/setup#L139

Suggested workaround: Use a different search delimited, e.g. `|`:

```
if [ -n "$CERTPATH" ] && [ -n "$KEYPATH" ]
then
    sed -i "s|#COTURN_TLS_CERT_PATH=.*|COTURN_TLS_CERT_PATH=$CERTPATH|" .env
    sed -i "s|#COTURN_TLS_KEY_PATH=.*|COTURN_TLS_KEY_PATH=$KEYPATH|" .env
fi
```
Cheers,
Stephan

**Comment by alangecker** [comment]
thanks for reporting this issue, it got now fixed with #144 :)
