### ISSUE TITLE
Docker file - not for production system

### ISSUE THREAD

**Issue by user18x** [bigbluebutton/docker#16]
Why is your docker file not for production systems?
If i use it i will use it on a production system!

**Comment by ffdixon** [comment]
We recommend running BigBlueButton on a dedicated server, see

  http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements

The docker file is good for understanding how BigBlueButton works, running a test server on different hardware (such as on a Mac), and development.  It's not for production.
