### ISSUE TITLE
Error while running docker 

### ISSUE THREAD

**Issue by satyaakam** [bigbluebutton/docker#17]
i  am trying to run docker using the command 

$docker run -p 80:80/tcp -p 443:443/tcp -p 1935:1935 -p 5066:5066 -p 3478:3478 -p 3478:3478/udp bigbluebutton/bigbluebutton -h 127.0.0.1

docker did not come up with the following errors  , i am trying to run the docker command on Linux Mint 19.1 

+ sed -i 's/deskshareip[ ]*=[ ]*"[^"]*"/deskshareip="127.0.0.1"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/defaultPresentationURL[ ]*=[ ]*"[^"]*"/defaultPresentationURL="http:\/\/127.0.0.1\/default.pdf"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ cat
++ openssl rand -hex 16
+ TURN_SECRET=b58ad153647a0cc2dd4288c15f024009
+ cat
+ cat
+ cat
++ cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
++ grep -v '#'
++ grep securitySalt
++ cut -d= -f2
+ SECRET=6bbdc14d32df911075a5f3176adc1a0f
+ sed -i 's/sharedSecret[ ]*=[ ]*"[^"]*"/sharedSecret="6bbdc14d32df911075a5f3176adc1a0f"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/BigBlueButtonURL = "http[s]*:\/\/\([^"\/]*\)\(["\/]\)/BigBlueButtonURL = "http:\/\/127.0.0.1\2/g' /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
+ sed -i 's/playback_host: .*/playback_host: 127.0.0.1/g' /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
+ sed -i 's/daemonize no/daemonize yes/g' /etc/redis/redis.conf
+ sed -i 's|"wsUrl.*|"wsUrl": "ws://127.0.0.1/bbb-webrtc-sfu",|g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings-production.json
+ rm /usr/share/red5/log/sip.log
rm: cannot remove '/usr/share/red5/log/sip.log': No such file or directory
+ sed -i 's/BigBlueButton.logger.debug("rap-archive-worker done")/sleep 20; BigBlueButton.logger.debug("rap-archive-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-process-worker done")/sleep 20; BigBlueButton.logger.debug("rap-process-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-sanity-worker done")/sleep 20 ; BigBlueButton.logger.debug("rap-sanity-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-publish-worker done")/sleep 20; BigBlueButton.logger.debug("rap-publish-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb
+ export NODE_ENV=production
+ NODE_ENV=production
+ export DAEMON_LOG=/var/log/kurento-media-server
+ DAEMON_LOG=/var/log/kurento-media-server
+ export 'GST_DEBUG=3,Kurento*:4,kms*:4'
+ GST_DEBUG='3,Kurento*:4,kms*:4'
+ export KURENTO_LOGS_PATH=/var/log/kurento-media-server
+ KURENTO_LOGS_PATH=/var/log/kurento-media-server
+ cat

BigBlueButton is now starting up at this address

  http://127.0.0.1

+ updatedb
/root/setup.sh: line 228: updatedb: command not found
+ exec /usr/bin/supervisord
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '

check the errors here if the readbility is an issue https://hastebin.com/cojawihaju.diff

**Comment by satyaakam** [comment]
this error has no bearing on how bbb runs in docker , i was able to test the demo flash as well as html5 client using firefox , but chrome gave error of not able to enable the microphone because there is no SSL certificate installed

**Comment by ffdixon** [comment]
Hi @satyaakam,

> this error has no bearing on how bbb runs in docker , i was able to test the demo flash as well as html5 client using firefox , but chrome gave error of not able to enable the microphone because there is no SSL certificate installed

Correct -- only FireFox will let you use WebRTC without a hostname + SSL certificate.  

We're working on updating the docker container to support 2.2-beta and will clean up a few of these error messages.

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
