### ISSUE TITLE
Install on Raspberry Pi

### ISSUE THREAD

**Issue by SuperDarius-git** [bigbluebutton/docker#170]
Good day

I get the following error when trying to generate the compose file. Please help!

_WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error_

**Comment by elearningdienst** [comment]
I think the docker deployment will only work on Intel compatible hardware.

**Comment by SuperDarius-git** [comment]
> I think the docker deployment will only work on Intel compatible hardware.

Thank you. :(

**Comment by alangecker** [comment]
jeps, there is no support for ARM processors and, to be honest, I won't see it ever coming since it requires a lot of work including recompiling most of the base images with probably a lot of now unexpected issues ;)
