### ISSUE TITLE
./scripts/setup: line 214: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by usshauler** [bigbluebutton/docker#172]
Every time I run the setup installer and it asks me if I want to include Prometheus exporter I answer no. It stops the install and gives me the following error.
./scripts/setup: line 214: syntax error: unexpected end of file

No matter how much I have tried to review setup file located within the scripts directory, I cannot find an issue in line 214 so I am assuming it has something to do with the file or how the script was written. Is there any solution for this in order for me to complete the docker install ?

**Comment by usshauler** [comment]
Never mind, I fixed the problem by adding a few double quotes near line 73 that were missing among a few other things.

**Comment by alangecker** [comment]
@usshauler 
were exactly were the quotes missing? Can't spot it, but would be cool if we would fix it for everyone :)

**Comment by usshauler** [comment]
![image](https://user-images.githubusercontent.com/49539369/145976612-55148fd4-0c38-49ff-a51f-886e6e8c9a87.png)

![image](https://user-images.githubusercontent.com/49539369/145976659-71af2b78-d536-47a6-97ab-36248b3222be.png)

**Comment by alangecker** [comment]
this was already fixed a while ago :)
