### ISSUE TITLE
POSTGRESQL_SECRET is using default value

### ISSUE THREAD

**Issue by hannob** [bigbluebutton/docker#173]
I noticed when setting up a bbb docker-compose instance that POSTGRESQL_SECRET was set to the default value from sample.env.

This seems to be caused by this condition:
```
if [ ! "$greenlight" == "y" ]
then
    sed -i "s/POSTGRESQL_SECRET=.*/POSTGRESQL_SECRET=$RANDOM_4/" .env
fi
```

Thus the secret only gets set to a random value if greenlight is not enable. I don't really see why that would be the case (maybe the intention was the reverse, i.e. only enable it when greenlight is used?).
In any case: It likely does not hurt to always randomize the secret, even if it is unused in some configurations.

**Comment by alangecker** [comment]
I've changed this now within https://github.com/bigbluebutton/docker/pull/159/commits/58f441f3ee2e53b803034647d3651de4e99c2820 which will be released with BBB 2.4 (#159)  ;)
