### ISSUE TITLE
why is there no prebuilt image?

### ISSUE THREAD

**Issue by dorianim** [bigbluebutton/docker#174]
Hi,

I love that bbb is now available as a docker image!
And I was wondering why it is necessary to build all images locally? Couldn'nt there just ne some prebuilt image on docker hub just like for greenlight?

Regards
Dorian

**Comment by alangecker** [comment]
It doesn't exist for the simple reason that no one has ever worked on it before :D

I would be happy if someone would take on this task :)

Requirements I would see:
- Should still be possible to build & use the images locally without push access to the docker hub
- Github CI script for building & pushing images
- Maybe some base images shared across containers for reduced download size, something like following: 

### base image for java containers (`apps-akka`, `bbb-web`, `fsesl-akka`)
```dockerfile
FROM openjdk:8-jre-slim-bullseye

RUN apt-get update && apt-get install -y \
        wget unzip gosu locales \
        imagemagick xpdf-utils curl

# add dockerize
ENV DOCKERIZE_VERSION v0.6.1
RUN wget -q https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

```

### base image for node containers (`html5`, `webhooks`, `webrtc-sfu`)
```dockerfile
FROM node:14-bullseye-slim

RUN apt-get update && apt-get -y install \
  git \
  make \
  python \
  python3-pip \
  g++ \
  ffmpeg \
  gosu
  
# add dockerize
ENV DOCKERIZE_VERSION v0.6.1
RUN wget -q https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
  
```
