### ISSUE TITLE
2.4 how to use mediasoup

### ISSUE THREAD

**Issue by dsjiern** [bigbluebutton/docker#176]
Hey,

can someone already say how to switch from kurento to mediasoup in the docker-variant?

thx

**Comment by alangecker** [comment]
with a brief look at the [instructions](https://github.com/bigbluebutton/bbb-webrtc-sfu/wiki/Back-of-the-envelope-calculations:-mediasoup) I see at least following steps:

- `webrtc-sfu` container
  * forward mediasoup ports or use host networking (latter would include changing networking references like in `mod/nginx/bbb/webrtc-sfu.nginx`)
  * maybe allow `SYS_NICE` real time priorities?
  * set 
    ```
    mediasoup.webrtc.listenIps[0].ip "0.0.0.0"
    mediasoup.webrtc.listenIps[0].announcedIp $EXTERNAL_IPv4
    mediasoup.webrtc.listenIps[1].ip $EXTERNAL_IPv6
    mediasoup.plainRtp.listenIp.ip "0.0.0.0"
    mediasoup.plainRtp.listenIp.announcedIp $EXTERNAL_IPv4
    ```
   * add mediasoup to `media-server-adapters`
-  `mod/html5/settings.yml` set
    ```
    public.kurento.screenshare.mediaServer
    public.kurento.videoMediaServer
    public.kurento.listenOnlyMediaServer
    ```
  
  
but I didn't try anything :D

**Comment by prlanzarin** [comment]
What @alangecker said should be correct. `add mediasoup to media-server-adapters` is not needed, though. Already set by default.

I skimmed through the updated Dockerfile for webrtc-sfu and it also seems correct (alpine -> slim, new deps are ok).

I'll try to test your v2.4.x branch with mediasoup this weekend, @alangecker, and give feedback.

**Comment by dsjiern** [comment]
>       * forward mediasoup ports or use host networking (latter would include changing networking references like in `mod/nginx/bbb/webrtc-sfu.nginx`)

thank you,
I can't find any informations about, which port's I have to forward... (and how? docker-compose.yml? 🙈)

when I just change the other points, the frontend tries to connect to mediasoup, but it failes with error 1107

for the settings in html5 it should be sufficient to change the lines 54-56 in webrtc-settings from Kurento to Mediasoup
```listenOnlyMediaServer: Kurento
videoMediaServer: Kurento
screenshareMediaServer: Kurento```

because in `html5/settings.yml`
```
# Default is undefined, which means the default setting in bbb-webrtc-sfu
# prevails (screenshareMediaServer).
```

**Comment by alangecker** [comment]
@dsjiern In the [webrtc-sfu config](https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/development/config/default.example.yml#L284) I found
```yaml
mediasoup:
  worker:
    rtcMinPort: 24577
    rtcMaxPort: 32768
```

maybe these ports are enough?^^ but I have no idea :D

to forward them append following in the `docker-compose.tmpl.yml`:

```yaml
  webrtc-sfu:
      ports:
      - "24577-32768/udp"
```

**Comment by prlanzarin** [comment]
If you're going the port-forward route then whatever is configured in rtcMinPort/rtcMaxPort.
But I'd recommend just running network host. It breaks network isolation in a way, but AFAIK port forwarding for large ranges is not that performant in docker containers (and this container is performance-sensitive).
