### ISSUE TITLE
Customising the landing page of Greenlight

### ISSUE THREAD

**Issue by miladbohlouli** [bigbluebutton/docker#177]
Hi,

How would it be possible to customize the landing page of the greenlight, the changes may include the coloring and the texts as well.

**Comment by ohli** [comment]
Basically, it's all described here: https://docs.bigbluebutton.org/admin/customize.html#modify-the-default-landing-page

To include this into docker, you have two options:
- clone the [greenlight container](https://github.com/bigbluebutton/greenlight), edit the needed files, rebuild
- add a volume to your existing greenlight container to overwrite the defaults

PS: sorry for necrobumping this, still less than a year
