### ISSUE TITLE
How to use docker image on http://play-with-docker.com ?

### ISSUE THREAD

**Issue by user18x** [bigbluebutton/docker#18]
I want to know how i can **test** BigBlueButton docker image/file on http://play-with-docker.com ?
Have installed on it but can't get access. :-(
Please help!

PS: Please do not close this!
Thanks!

**Comment by satyaakam** [comment]
tried this inside the play ground 
$docker pull bigbluebutton/bigbluebutton
$ docker run 1678f9acf03c
+ getopts eh: opt
+ apt-get install -y bbb-demo
Reading package lists...
Building dependency tree...
Reading state information...
bbb-demo is already the newest version (1:2.0.0-14).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
+ /etc/init.d/tomcat7 start
 * Starting Tomcat servlet engine tomcat7
   ...done.
+ '[' '!' -f /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp ']'
+ sudo /etc/init.d/tomcat7 stop
 * Stopping Tomcat servlet engine tomcat7
   ...done.
+ PROTOCOL_HTTP=http
+ PROTOCOL_RTMP=rtmp
++ head -n1
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
+++ grep addr:
+++ grep '^et.*'
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep addr:
+++ grep '^en.*'
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
+++ head -n1
++ echo 172.17.0.2
+ IP=172.17.0.2
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "external_rtp_ip=")]/@data' --value stun:coturn /opt/freeswitch/conf/vars.xml
/root/setup.sh: line 74: xmlstarlet: command not found
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "external_sip_ip=")]/@data' --value stun:coturn /opt/freeswitch/conf/vars.xml
/root/setup.sh: line 75: xmlstarlet: command not found
+ xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@data, "local_ip_v4=")]/@data' --value 172.17.0.2 /opt/freeswitch/conf/vars.xml
/root/setup.sh: line 76: xmlstarlet: command not found
+ sed -i 's/proxy_pass .*/proxy_pass http:\/\/172.17.0.2:5066;/g' /etc/bigbluebutton/nginx/sip.nginx
+ sed -i 's/http[s]*:\/\/\([^"\/]*\)\(["\/]\)/http:\/\/\2/g' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/rtmp[s]*:\/\/\([^"\/]*\)\(["\/]\)/rtmp:\/\/\2/g' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/server_name  .*/server_name  ;/g' /etc/nginx/sites-available/bigbluebutton
+ sed -i 's/bigbluebutton.web.serverURL=http[s]*:\/\/.*/bigbluebutton.web.serverURL=http:\/\//g' /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties streamBaseUrl rtmp:///screenshare
+ sed -i 's<^[[:blank:]#]*\(streamBaseUrl\).*<\1=rtmp:///screenshare<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpUrl http:///screenshare
+ sed -i 's<^[[:blank:]#]*\(jnlpUrl\).*<\1=http:///screenshare<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
+ change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpFile http:///screenshare/screenshare.jnlp
+ sed -i 's<^[[:blank:]#]*\(jnlpFile\).*<\1=http:///screenshare/screenshare.jnlp<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
+ change_var_value /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties bbb.sip.app.ip 172.17.0.2
+ sed -i 's<^[[:blank:]#]*\(bbb.sip.app.ip\).*<\1=172.17.0.2<' /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
+ change_var_value /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties freeswitch.ip 172.17.0.2
+ sed -i 's<^[[:blank:]#]*\(freeswitch.ip\).*<\1=172.17.0.2<' /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
+ sed -i 's/bbbWebAPI[ ]*=[ ]*"[^"]*"/bbbWebAPI="http:\/\/\/bigbluebutton\/api"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/bbbWebHost[ ]*=[ ]*"[^"]*"/bbbWebHost=""/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/deskshareip[ ]*=[ ]*"[^"]*"/deskshareip=""/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/defaultPresentationURL[ ]*=[ ]*"[^"]*"/defaultPresentationURL="http:\/\/\/default.pdf"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ cat
++ openssl rand -hex 16
+ TURN_SECRET=00a3d2c34f487ee329ebaceb8431160f
+ cat
+ cat
+ cat
++ cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
++ grep -v '#'
++ grep securitySalt
++ cut -d= -f2
+ SECRET=6bbdc14d32df911075a5f3176adc1a0f
+ sed -i 's/sharedSecret[ ]*=[ ]*"[^"]*"/sharedSecret="6bbdc14d32df911075a5f3176adc1a0f"/g' /usr/share/bbb-apps-akka/conf/application.conf
+ sed -i 's/BigBlueButtonURL = "http[s]*:\/\/\([^"\/]*\)\(["\/]\)/BigBlueButtonURL = "http:\/\/\2/g' /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
+ sed -i 's/playback_host: .*/playback_host: /g' /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
+ sed -i 's/daemonize no/daemonize yes/g' /etc/redis/redis.conf
+ sed -i 's|"wsUrl.*|"wsUrl": "ws:///bbb-webrtc-sfu",|g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings-production.json
+ rm /usr/share/red5/log/sip.log
rm: cannot remove '/usr/share/red5/log/sip.log': No such file or directory
+ sed -i 's/BigBlueButton.logger.debug("rap-archive-worker done")/sleep 20; BigBlueButton.logger.debug("rap-archive-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-process-worker done")/sleep 20; BigBlueButton.logger.debug("rap-process-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-sanity-worker done")/sleep 20 ; BigBlueButton.logger.debug("rap-sanity-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb
+ sed -i 's/BigBlueButton.logger.debug("rap-publish-worker done")/sleep 20; BigBlueButton.logger.debug("rap-publish-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb
+ export NODE_ENV=production
+ NODE_ENV=production
+ export DAEMON_LOG=/var/log/kurento-media-server
+ DAEMON_LOG=/var/log/kurento-media-server
+ export 'GST_DEBUG=3,Kurento*:4,kms*:4'
+ GST_DEBUG='3,Kurento*:4,kms*:4'
+ export KURENTO_LOGS_PATH=/var/log/kurento-media-server
+ KURENTO_LOGS_PATH=/var/log/kurento-media-server
+ cat

BigBlueButton is now starting up at this address

  http://

+ updatedb
/root/setup.sh: line 228: updatedb: command not found
+ exec /usr/bin/supervisord
/usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '

@user18x did you try this ?

**Comment by user18x** [comment]
Yes, i've tried some times
docker pull bigbluebutton/bigbluebutton
docker run 1678f9acf03c

and it's running, but i can get the address for the browser url.

**Comment by ffdixon** [comment]
@user18x, we've not tried this site before -- we're in progress of updating the docker image for BigBlueButton 2.2-beta and we'll give this site a try with the newer image.

**Comment by user18x** [comment]
Ok, so you will test at play-with-docker.com wirth v2.2 beta?
Do you know a release date of the docker image 2.2 beta?

**Comment by satyaakam** [comment]
yes it would be interesting to see docker running inside docker :-)

**Comment by Aoleara** [comment]
Violadores soy la dueña de todos esos datos robados y manipulados y víctima de un abuso brutal. Cobardes.

**Comment by Aoleara** [comment]
Esta denunciado la licencia no es válida. Todo es ilegal y hay pruebas ala corte internacional y de derechos humanis

**Comment by Aoleara** [comment]
Larkin enfermo psicópata

**Comment by Aoleara** [comment]
Todos los nombres, tb Gómez, Horowitz pressimone, larkin wisd.... Denunciados

**Comment by Aoleara** [comment]
Vais a tener q jugar con vuestra madre, ya me entendeis

**Comment by Aoleara** [comment]
Denuncia.... Violadores, AOSADores y pederastas. Me dais nauseas

**Comment by Aoleara** [comment]
Si algo me da realmente asco son las manadas de cobardes

**Comment by Aoleara** [comment]
Y el otro repositorio llamado game 64 aviso a quien lo utilice q a lo mejor termina como estos nabosos nauseabundo arrastrados

**Comment by Aoleara** [comment]
> tried this inside the play ground
> $docker pull bigbluebutton/bigbluebutton
> $ docker run 1678f9acf03c
> 
> * getopts eh: opt
> * apt-get install -y bbb-demo
>   Reading package lists...
>   Building dependency tree...
>   Reading state information...
>   bbb-demo is already the newest version (1:2.0.0-14).
>   0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> * /etc/init.d/tomcat7 start
> 
> * Starting Tomcat servlet engine tomcat7
>   ...done.
> 
> * '[' '!' -f /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp ']'
> * sudo /etc/init.d/tomcat7 stop
> 
> * Stopping Tomcat servlet engine tomcat7
>   ...done.
> 
> * PROTOCOL_HTTP=http
> * PROTOCOL_RTMP=rtmp
>   ++ head -n1
>   +++ LANG=c
>   +++ ifconfig
>   +++ awk -v RS= '{gsub (/\n[ ]_inet /," ")}1'
>   +++ head -n1
>   +++ sed 's/._addr://g'
>   +++ sed 's/ ._//g'
>   +++ grep addr:
>   +++ grep '^et._'
>   +++ LANG=c
>   +++ ifconfig
>   +++ awk -v RS= '{gsub (/\n[ ]_inet /," ")}1'
>   +++ grep addr:
>   +++ grep '^en._'
>   +++ sed 's/._addr://g'
>   +++ sed 's/ ._//g'
>   +++ head -n1
>   ++ echo 172.17.0.2
> * IP=172.17.0.2
> * xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@DaTa, "external_rtp_ip=")]/@DaTa' --value stun:coturn /opt/freeswitch/conf/vars.xml
>   /root/setup.sh: line 74: xmlstarlet: command not found
> * xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@DaTa, "external_sip_ip=")]/@DaTa' --value stun:coturn /opt/freeswitch/conf/vars.xml
>   /root/setup.sh: line 75: xmlstarlet: command not found
> * xmlstarlet edit --inplace --update '//X-PRE-PROCESS[@cmd="set" and starts-with(@DaTa, "local_ip_v4=")]/@DaTa' --value 172.17.0.2 /opt/freeswitch/conf/vars.xml
>   /root/setup.sh: line 76: xmlstarlet: command not found
> * sed -i 's/proxy_pass .*/proxy_pass http://172.17.0.2:5066;/g' /etc/bigbluebutton/nginx/sip.nginx
> * sed -i 's/http[s]_://([^"/]_)(["/])/http://\2/g' /var/www/bigbluebutton/client/conf/config.xml
> * sed -i 's/rtmp[s]_://([^"/]_)(["/])/rtmp://\2/g' /var/www/bigbluebutton/client/conf/config.xml
> * sed -i 's/server_name  .*/server_name  ;/g' /etc/nginx/sites-available/bigbluebutton
> * sed -i 's/bigbluebutton.web.serverURL=http[s]_://._/bigbluebutton.web.serverURL=http:///g' /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
> * change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties streamBaseUrl rtmp:///screenshare
> * sed -i 's<^[[:blank:]#]_(streamBaseUrl)._<\1=rtmp:///screenshare<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
> * change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpUrl http:///screenshare
> * sed -i 's<^[[:blank:]#]_(jnlpUrl)._<\1=http:///screenshare<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
> * change_var_value /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties jnlpFile http:///screenshare/screenshare.jnlp
> * sed -i 's<^[[:blank:]#]_(jnlpFile)._<\1=http:///screenshare/screenshare.jnlp<' /usr/share/red5/webapps/screenshare/WEB-INF/screenshare.properties
> * change_var_value /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties bbb.sip.app.ip 172.17.0.2
> * sed -i 's<^[[:blank:]#]_(bbb.sip.app.ip)._<\1=172.17.0.2<' /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
> * change_var_value /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties freeswitch.ip 172.17.0.2
> * sed -i 's<^[[:blank:]#]_(freeswitch.ip)._<\1=172.17.0.2<' /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
> * sed -i 's/bbbWebAPI[ ]_=[ ]_"[^"]*"/bbbWebAPI="http:///bigbluebutton/api"/g' /usr/share/bbb-apps-akka/conf/application.conf
> * sed -i 's/bbbWebHost[ ]_=[ ]_"[^"]*"/bbbWebHost=""/g' /usr/share/bbb-apps-akka/conf/application.conf
> * sed -i 's/deskshareip[ ]_=[ ]_"[^"]*"/deskshareip=""/g' /usr/share/bbb-apps-akka/conf/application.conf
> * sed -i 's/defaultPresentationURL[ ]_=[ ]_"[^"]*"/defaultPresentationURL="http:///default.pdf"/g' /usr/share/bbb-apps-akka/conf/application.conf
> * cat
>   ++ openssl rand -hex 16
> * TURN_SECRET=00a3d2c34f487ee329ebaceb8431160f
> * cat
> * cat
> * cat
>   ++ cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
>   ++ grep -v '#'
>   ++ grep securitySalt
>   ++ cut -d= -f2
> * SECRET=6bbdc14d32df911075a5f3176adc1a0f
> * sed -i 's/sharedSecret[ ]_=[ ]_"[^"]*"/sharedSecret="6bbdc14d32df911075a5f3176adc1a0f"/g' /usr/share/bbb-apps-akka/conf/application.conf
> * sed -i 's/BigBlueButtonURL = "http[s]_://([^"/]_)(["/])/BigBlueButtonURL = "http://\2/g' /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
> * sed -i 's/playback_host: .*/playback_host: /g' /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
> * sed -i 's/daemonize no/daemonize yes/g' /etc/redis/redis.conf
> * sed -i 's|"wsUrl.*|"wsUrl": "ws:///bbb-webrtc-sfu",|g' /usr/share/meteor/bundle/programs/server/assets/app/config/settings-production.json
> * rm /usr/share/red5/log/sip.log
>   rm: cannot remove '/usr/share/red5/log/sip.log': No such file or directory
> * sed -i 's/BigBlueButton.logger.debug("rap-archive-worker done")/sleep 20; BigBlueButton.logger.debug("rap-archive-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb
> * sed -i 's/BigBlueButton.logger.debug("rap-process-worker done")/sleep 20; BigBlueButton.logger.debug("rap-process-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb
> * sed -i 's/BigBlueButton.logger.debug("rap-sanity-worker done")/sleep 20 ; BigBlueButton.logger.debug("rap-sanity-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb
> * sed -i 's/BigBlueButton.logger.debug("rap-publish-worker done")/sleep 20; BigBlueButton.logger.debug("rap-publish-worker done")/g' /usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb
> * export NODE_ENV=production
> * NODE_ENV=production
> * export DAEMON_LOG=/var/log/kurento-media-server
> * DAEMON_LOG=/var/log/kurento-media-server
> * export 'GST_DEBUG=3,Kurento*:4,kms*:4'
> * GST_DEBUG='3,Kurento*:4,kms*:4'
> * export KURENTO_LOGS_PATH=/var/log/kurento-media-server
> * KURENTO_LOGS_PATH=/var/log/kurento-media-server
> * cat
> 
> BigBlueButton is now starting up at this address
> 
> http://
> 
> * updatedb
>   /root/setup.sh: line 228: updatedb: command not found
> * exec /usr/bin/supervisord
>   /usr/lib/python2.7/dist-packages/supervisor/options.py:297: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
>   'Supervisord is running as root and it is searching '
> 
> @user18x did you try this ?

Y tu intentaste usar a tu madre? Estoy segura de q si

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
