### ISSUE TITLE
upgrade to 2.4 failed with non-zero code: 137 bigbluebutton-html5

### ISSUE THREAD

**Issue by mokkin** [bigbluebutton/docker#187]
```
make: Leaving directory '/home/meteor/source/node_modules/fibers/build'
Installed in `/home/meteor/source/node_modules/fibers/bin/linux-x64-83-glibc/fibers.node`
added 403 packages in 43.571s
WARNING: version mismatch for node-sass; installed version is 6.0.1, but version >=3.x <=4.x is required by nathantreid:css-modules)
WARNING: version mismatch for node-sass; installed version is 6.0.1, but version >=3.x <=4.x is required by nathantreid:css-modules)
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Killed
ERROR: Service 'html5-frontend-1' failed to build: The command '/bin/sh -c cd ~     && svn checkout https://github.com/bigbluebutton/bigbluebutton/tags/$TAG/bigbluebutton-html5     && mv ~/bigbluebutton-html5 ~/source     && cd ~/source     && ~/.meteor/meteor npm ci --production     && METEOR_DISABLE_OPTIMISTIC_CACHING=1  ~/.meteor/meteor build --architecture os.linux.x86_64 --directory ~/app     && rm -rf ~/source' returned a non-zero code: 137
```

**Comment by alangecker** [comment]
sounds like you are running out of memory during the build process, which needs a lot.
is it possible that you have less than ~3GB of free memory? :)

a quick solution could be adding a swapfile

**Comment by mokkin** [comment]
Indeed I have no swap partition, but I never had memory issues before. Not in the original build process one year ago and not during usage over the last month.
The total memory is 4GB and there is only BBB via docker on the machine.

**Comment by mokkin** [comment]
As a workaround I stopped all containers to run the upgrade.
Maybe you can add stopping them to you script?

**Comment by alangecker** [comment]
since already a while the default became using prebuilt docker images published at [docker hub](https://hub.docker.com/u/alangecker) instead of self building with huge memory requirements, so I guess this issue can be closed
