### ISSUE TITLE
Sending Emails not working

### ISSUE THREAD

**Issue by NoobKeksTV** [bigbluebutton/docker#193]
I have the problem that after updating to the latest version of BBB-Docker, sending invit emails doesnt work. It seems like my mailserver (mailcow-dockerized) running on the same server doesnt even get a connection from bbb (checked postfix logs, no connection)

These are my SMTP setting inside of my .env file
Note that these exact settings have worked fine befor!
```
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_SERVER=mail.xxx.com
SMTP_PORT=587
SMTP_DOMAIN=bbb.xxx.com
SMTP_USERNAME=noreply@xxx.com
SMTP_PASSWORD=xxx
SMTP_AUTH=login
SMTP_STARTTLS_AUTO=true

# Specify the email address that all mail is sent from
SMTP_SENDER=DerGroßeBlaueKnopf 
```

**Comment by lexuzieel** [comment]
I had a similar issue. You can debug if the SMTP config is actually recognized by running:

```
docker-compose exec greenlight bundle exec rake conf:check
```

For me it didn't even mention SMTP, so completely restarting the whole project made it working for me.

**Comment by ZockerBoysHD** [comment]
tried this and it says this:

`Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Failed
Error connecting to SMTP - execution expired
`

however out other software & clients are able connect to the mail server with these exact adress, port, email login & passwort. 
Does it have something to do with it being in a docker container?
Or could it be that i diisabled conections to our server origin ip so only cloudflare connections work. But again other websites we have use ethe exact same login info & are on the same host so if firewall is an issue, they should also not work but they all work without problems.

**Comment by lexuzieel** [comment]
In my setup I don't have `SMTP_OPENSSL_VERIFY_MODE` specified. Also I am not sure but is it possible that `ß` character in sender name throws your SMTP server off? Oh and I just noticed that `SMTP_SENDER` doesn't follow `name@domain.com` pattern - could that also be a reason?

**Comment by alangecker** [comment]
these are greenlight configs, rather unrelated to bbb-docker and probably after a year resolved?
if still an issue, rather ask at greenlight mailing list https://groups.google.com/forum/#!forum/bigbluebutton-greenlight
