### ISSUE TITLE
apt-get install fails inside container (apt-show-version), with workaround.

### ISSUE THREAD

**Issue by JohnnyC1951** [bigbluebutton/docker#2]
The problem, cause & fix are shown here: [https://groups.google.com/forum/#!topic/beagleboard/jXb9KhoMOsk](url)
Running these INSIDE the container, one at a time, fixes it:
`rm /etc/apt/apt.conf.d/docker-gzip-indexes`
`apt-get purge apt-show-versions`
`rm /var/lib/apt/lists/*lz4`
`apt-get -o Acquire::GzipIndexes=false update`
`apt-get install apt-show-versions`

**Comment by neutron92** [comment]
how to allow th http to use Mic and the Camera in several browsers

**Comment by umtcn-krkmz** [comment]
you can just try have an update inside the container

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
