### ISSUE TITLE
webrtc fails

### ISSUE THREAD

**Issue by SriramScorp** [bigbluebutton/docker#20]
I used the Dockerfile to build an image and deployed an instance. However, the webrtc connection fails and keeps defaulting to flash audio. Considering that we are running an instance of coturn alongside, shouldn't the webrtc supposed to work out of the box? If not, is it necessary that the turn server should be outside the NAT infrastructure of the bigbluebutton docker setup for webrtc to work?

**Comment by ffdixon** [comment]
It should work -- we're in the process of updating the docker image to use BigBlueButton 2.2-beta (and only use HTML5 client).

Look for an update to this issue when we've got the docker scripts updated.  BigBlueButton 2.2-beta is still in development, which is the focus of our efforts at the moment.

**Comment by Aoleara** [comment]
Veréis expuestos vuestros cuños en la cEcel

**Comment by Aoleara** [comment]
Carcel

**Comment by nigel-dewar** [comment]
Hi @ffdixon , how for did you get with 2.2-beta with docker? cheers

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
