### ISSUE TITLE
bbb-docker-base-java Image not pullable

### ISSUE THREAD

**Issue by dsjiern** [bigbluebutton/docker#212]
Hey,

thank you very much for the changes!

But now I get following error:

```
pull access denied for bbb-docker-base-java, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
ERROR: Service 'bbb-web' failed to build : Build failed
```

🤔 I do have the `bbb-docker-base-java` image locally (from last build 10 days ago), and I can run it with `docker run --rm -it bbb-docker-base-java bash` and I'm unable to pull the latest image, so the build for `bbb-web` failed.

**Comment by alangecker** [comment]
it is built within `./scripts/upgrade`, but please don't open more issues to `2.5` as long as it is work in progress. :D
Discussion to the current development belongs in https://github.com/bigbluebutton/docker/pull/207
