### ISSUE TITLE
File is too large, exceeded the maximum of {0} MB

### ISSUE THREAD

**Issue by Skiller899** [bigbluebutton/docker#214]
Hi, I have a problem with docker version BBB 2.4. It still gives me the message: "File is too large, exceeded the maximum of {0} MB" when I upload a file larger than 2 MB.  
What do I need to change and where? I have already tried to look at all the options on the internet and nothing worked properly.

**Comment by merzi** [comment]
I got the same problem in the room overview, if the conference is not started.

For me worked it to add the config entry client_max_body_size in the server part of the bigbluebutton nginx config file.

You can find the config at [mod](https://github.com/bigbluebutton/docker/tree/develop/mod)/[nginx](https://github.com/bigbluebutton/docker/tree/develop/mod/nginx)/[bigbluebutton](https://github.com/bigbluebutton/docker/tree/develop/mod/nginx/bigbluebutton).

i set a realy generous value of 15M, maybe you can choose a lower value.

**Comment by Skiller899** [comment]
Hi, I tried to change it, also directly in nginx. Even in the file you recommend, but neither helped.

**Comment by merzi** [comment]
if you edited the config file inside of the running container, the nginx service must be restarted. At this point the container restarts and the changes will be unset.

the easiest way is to change the config file in the given path and rebuild the nginx container the docker build command or use the upgrade script in the scripts folder. Then a container with the given config will be build and use this from start.

**Comment by drlight17** [comment]
BBB docker 2.5 - still having such problem. Tried to modify at the same time:
1)  /bbb-docker/mod/html5/bbb-html5.yml with
presentation:
    # mirroredFromBBBCore are values controlled in bbb-web properties file. We include a copy here for notification purposes
    mirroredFromBBBCore:
      uploadSizeMax: 50000000
2) /bbb-docker/mod/nginx/bbb/web.nginx with
client_max_body_size       50m;
3) /bbb-docker/mod/bbb-web# ./bbb-web.properties with 
maxFileSizeUpload=50000000
Docker containers were rebuilt after changes, but still getting the same error. Could someone point me what am I doing wrong?

**Comment by drlight17** [comment]
Just found out that in my case it was nginx reverse proxy where I forgot to add client_max_body_size 50m;
Problem solved.

**Comment by zguig52** [comment]
Hi, just got also into the same issue:
I had to change this client_max_body_size configuration :
1. On the reverse proxy (for live upload during the presentation) / like @drlight17 
2. On the docker nginx configuration file (for upload when the meeting is not running, via the room menu -> add presentation):
`vi mod/nginx/nginx.conf
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 100M;
...
`
Then rebuild the containers to take the changes in account: docker-compose build
Then restart the changed containers: docker-compose up -d

**Comment by alangecker** [comment]
thanks to @nr23730  this should be now resolved with #252
