### ISSUE TITLE
Recordings failing with missing ffmpeg filter 'tpad'

### ISSUE THREAD

**Issue by lightweight** [bigbluebutton/docker#235]
We don't do much recording on our BBB instance, but following our recent upgrade to 2.5.5 via `sudo ./scripts/upgrade-and-build` we have not been able to get a successful recording. The processing of each one fails with an error like (from the recording containers /var/log/bigbluebutton/recording.log):

```
Executing: ffmpeg -y -v warning -nostats -max_error_rate 1.0 -ss 0.000 -i /var/bigbluebutton/recording/raw/c9c5b752be70b4559f23c358883c18b51e446761-1666838764926/video/c9c5b752be70b4559f23c358883c18b51e446761-1666838764926/medium-w_fxkowra0itrn-1666838784928.webm -filter_complex_script /var/bigbluebutton/recording/process/presentation/c9c5b752be70b4559f23c358883c18b51e446761-1666838764926/webcams_0.mp4.filter -an -codec libx264 -preset veryfast -crf 30 -force_key_frames expr:gte\(t,n_forced\*10\) -pix_fmt yuv420p -r 15 /var/bigbluebutton/recording/process/presentation/c9c5b752be70b4559f23c358883c18b51e446761-1666838764926/webcams_0.mp4
[AVFilterGraph @ 0x55ed330cc400] No such filter: 'tpad'
Error initializing complex filters.
Invalid argument
Success?: false
```

Another instance I run using the same configuration (but first created more recently) and also upgraded to 2.5.5 recently doesn't seem to have this problem. Apparently according to https://stackoverflow.com/questions/73523288/ffmpeg-no-such-filter-tpad the 'tpad' filter was only introduced in v4.2. The ffmpeg installed on the recordings container is version v4.1.9... 

I've replaced the ffmpeg in the container with a newer binary (temporarily) and the recording is generated & published without error. Could a dependency update fix this, or avoiding the use of 'tpad' for now?

**Comment by lightweight** [comment]
Ok - I've tested one of my other BBB instances again, and it appears that recording rendering fails with the same 'tpad' filter error on ffmpeg there as it is on the main BBB instance. So this seems to be a version-specific issue: outdated FFMPEG in the recording container.

**Comment by kodukon** [comment]
I have bbb v2.5.5 instance and I had similar issue. I was edit Dockerfile of "recordings" container by @lightweight instructions and its work for me. Thanks!

**Comment by babatonga** [comment]
Same Issue here, for fixing it I used a static ffmpeg build and put it directly inside the docker Container to /usr/local/bin/ffmpeg and /usr/local/bin/ffprobe following this manual: https://www.johnvansickle.com/ffmpeg/faq/

I was lazy and just entered bash from the recordings container via
`docker exec -it bbb-docker-recordings-1 bash`

**Comment by alangecker** [comment]
I've seen that bullseye offers also a more recent version of ffmpeg (`4.3.5-0+deb11u1`). Simply switching to `ruby:2.7-slim-bullseye` as the base image seems therefore to also resolve that issue :)

-> #239
