### ISSUE TITLE
"Drift" between video and audio (with audio delayed more than videao)

### ISSUE THREAD

**Issue by lightweight** [bigbluebutton/docker#237]
We're experiencing significant (distracting) audio drift on a couple up-to-date BBB instances, deployed using Docker (currently at 2.5.5). I see this issue on the main BBB codebase https://github.com/bigbluebutton/bigbluebutton/issues/15776 and I'm trying to figure out if I can apply the tweaks to files shown in https://github.com/bigbluebutton/bigbluebutton/pull/15766/files - unfortunately I can't seem to find those files to change in the freeswitch container... Any idea when the fixes for 2.5.7 will be applied to the Docker containers (which still seem to be on 2.5.5)?

**Comment by ffdixon** [comment]
You should get better performance with 2.5.8.  Is it an option for you to try an install with `bbb-install.sh` on a server (not docker) until the docker containers are updated?

**Comment by lightweight** [comment]
Hi Fred, sadly it's not easy to run a non-Docker install at the moment. Anything I can do to help with updating the Docker reference containers?

**Comment by ffdixon** [comment]
I'm not familiar with the setup and configuration of the Docker containers in this repository.  But if you could make the changes, or at least minimally 

  https://github.com/bigbluebutton/bigbluebutton/commit/aa0fdb8727bb371958c04870deb3d178d08b7315

You would reduce the drift.

**Comment by alangecker** [comment]
@lightweight 
the current `2.5.8` release includes the freeswitch config changes 
maybe an `./scripts/upgrade` could therefore fix your issue? :)

**Comment by lightweight** [comment]
You beauty!  Saves me doing a pull request :) - I just applied those files (https://github.com/bigbluebutton/bigbluebutton/blob/aa0fdb8727bb371958c04870deb3d178d08b7315/bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml and https://github.com/bigbluebutton/bigbluebutton/blob/aa0fdb8727bb371958c04870deb3d178d08b7315/bbb-voice-conference/config/freeswitch/conf/dialplan/default/bbb_conference.xml) to my instance as a temporary fix, and it's working (v2.5.2). After our 'big meeting' tomorrow, I'll do the upgrade to 2.5.8! Many thanks for your continued updates to the docker containers! Let me know if you ever need help with it!
