### ISSUE TITLE
Stuck at "Establishing audio connection"

### ISSUE THREAD

**Issue by DBLouis** [bigbluebutton/docker#247]
I installed bigbluebutton with Docker following the instructions in this repo, including the ones to configure the reverse proxy (nginx on the host).

The web page is reachable and "working" but when joining a room the audio setup is hanging with "Establishing audio connection" forever.

I edited the .env file to use my STUN and TURN server running on the host machine. The issue does not come from the TURN server because it was working before, with bigbluebutton installed on a separated machine. (instead of docker).

One of the container logs shows the following error repeatedly, might be related:

```
2023-01-01T15:41:32.951Z INFO  o.b.f.v.f.ConnectionManager - Attempting to connect to FreeSWITCH ESL
2023-01-01T15:41:32.965Z WARN  o.f.e.c.i.InboundClientHandler - connection timed out
```

Other containers logs show no errors.

**Comment by DBLouis** [comment]
Is is possible that hosting STUN and TURN server on the host machine poses a problem?

**Comment by DBLouis** [comment]
Fi

**Comment by ffdixon** [comment]
Thanks for sharing this @DBLouis.  Do you think we need updates to the docs or code?

**Comment by DBLouis** [comment]
No problem, maybe add something to the README about firewall. I had to do `ufw allow from 10.7.7.0/24` .
