### ISSUE TITLE
Freeswitch compression cannot be enabled when max file count is 1

### ISSUE THREAD

**Issue by aurorasmiles** [bigbluebutton/docker#260]
Got an `Error response from daemon: compression cannot be enabled when max file count is 1` after upgrading to v2.6. I assume https://github.com/bigbluebutton/docker/commit/d5164ecef937dcfd74c9c2993a88f4a65ce1337c caused this

**Comment by yanus** [comment]
Same here, adding `compress: "false"` to the logging options gets rid of the error.

**Comment by alangecker** [comment]
dammit, I was quite sloppy with that commit.

a `./scripts/upgrade` should fix it now
