### ISSUE TITLE
Interest on keycloak integration

### ISSUE THREAD

**Issue by merzi** [bigbluebutton/docker#265]
With Greenlight 3 the default authentification against 3rd parties is running over the extra application named keycloak.

i have implement keycloak in a fork and my question is, is here any interest on it or not.

The setup and generate-compose script has been extented for installation of the keycloak container and the nginx configuration has been extented. There is only little problem on the database initialisation of keycloak. If here is interesst i spend time to implement something and make a pr.

**Comment by merzi** [comment]
#323

**Comment by BennHi** [comment]
@merzi do I understand correctly, that your fork is not yet verified to be working fine? I'm interested in deploying it but I don't have the know how to judge your changes
