### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by iangilmour** [bigbluebutton/docker#27]
One of the ppa's used is now private. As a result the docker build step fails with: 

`Step 12/38 : RUN apt-get update && apt-get -y dist-upgrade
 ---> Running in c1c9addee497
Ign:1 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Get:5 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease [18.0 kB]
Hit:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:7 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial Release
Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages
Hit:10 http://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease
Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages
Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages
Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages
Err:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages
  403  Forbidden
Get:11 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main amd64 Packages [382 B]
Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages
Fetched 18.4 kB in 0s (19.6 kB/s)
Reading package lists...
W: The repository 'http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get -y dist-upgrade' returned a non-zero code: 100
user@devsys:~/src/bigbluebutton$ 
`

Is there an alternative?

**Comment by ffdixon** [comment]
Can you use the following PPA instead of `jonathanf`
Could you try changing 

  https://github.com/bigbluebutton/docker/blob/master/Dockerfile#L16

to read

~~~
RUN add-apt-repository ppa:bigbluebutton/support -y
~~~

**Comment by iangilmour** [comment]
Thanks - it gets further into the build, but still fails unfortunately. See attached: 
[bbb.log](https://github.com/bigbluebutton/docker/files/3991672/bbb.log)

**Comment by Aoleara** [comment]
Si seguís con esto sabed q todos los nombres están dwnunciados

**Comment by Aoleara** [comment]
> One of the ppa's used is now private. As a result the docker build step fails with:
> 
> `Step 12/38 : RUN apt-get update && apt-get -y dist-upgrade ---> Running in c1c9addee497 Ign:1 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial InRelease Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease Hit:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease Get:5 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease [18.0 kB] Hit:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease Ign:7 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial Release Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages Hit:10 http://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages Ign:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages Err:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages 403 Forbidden Get:11 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main amd64 Packages [382 B] Ign:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main all Packages Fetched 18.4 kB in 0s (19.6 kB/s) Reading package lists... W: The repository 'http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial Release' does not have a Release file. E: Failed to fetch http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu/dists/xenial/main/binary-amd64/Packages 403 Forbidden E: Some index files failed to download. They have been ignored, or old ones used instead. The command '/bin/sh -c apt-get update && apt-get -y dist-upgrade' returned a non-zero code: 100 user@devsys:~/src/bigbluebutton$ `
> 
> Is there an alternative?

Si, q vayáis a la carcel

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
