### ISSUE TITLE
building bbb-pads fails

### ISSUE THREAD

**Issue by bjo81** [bigbluebutton/docker#272]
While running `docker-compose up -d`:

```
Building bbb-pads
Sending build context to Docker daemon  3.584kB
Step 1/10 : FROM node:16-bullseye-slim AS builder
16-bullseye-slim: Pulling from library/node
9e3ea8720c6d: Pull complete 
22cee24855b2: Pull complete 
4ebaa3579fba: Pull complete 
b31e2dbd8a1c: Pull complete 
1a6527404bb4: Pull complete 
Digest: sha256:7ee0b958bd5f47f54b58f2b9932b1975a4d98d8f332bd2134c2b65514cadb6c6
Status: Downloaded newer image for node:16-bullseye-slim
 ---> ffd36734ebe8
Step 2/10 : COPY ./bbb-pads /bbb-pads
 ---> 701a2cbd74c6
Step 3/10 : RUN cd /bbb-pads && rm -r .git && npm install --production
 ---> Running in 46f1a5742d67
rm: cannot remove '.git': No such file or directory
The command '/bin/sh -c cd /bbb-pads && rm -r .git && npm install --production' returned a non-zero code: 1
ERROR: Service 'bbb-pads' failed to build : Build failed
```
There is no `.git` in mod/bbb-pads.

**Comment by bjo81** [comment]
Recurse Submodules were missing.

**Comment by J0J0HA** [comment]
> Recurse Submodules were missing.

Can you tell me how you fixed this? From your reply I figured `git submodule update --recursive` might fix it, but it didn't.

**Comment by bjo81** [comment]
Did you run `docker compose up -d --no-build`? Seems like since 07ce2c483ccd8820b782874a2930a10007d3b055 building isn't necessary.

**Comment by J0J0HA** [comment]
Yes I did, but I got problems I thought building might fix. I figured out how to get the submodules, and building worked, but it didn't fix my initial problem. (Issue #312)

Thank you anyways :)
