### ISSUE TITLE
400 error when trying to start a room, also certs are not created 

### ISSUE THREAD

**Issue by rycaputo** [bigbluebutton/docker#286]
Request URL:
https://10.100.0.32/api/v1/meetings/eq2-is7-w6q-nsk/start.json
Request Method:
POST
Status Code:
400
Remote Address:
10.100.0.32:443
Referrer Policy:
strict-origin-when-cross-origin

also 

coturn_1               | ERROR: certificate doesn't exist yet.
coturn_1               | Certificate gets create on the first request to the HTTPS proxy.
coturn_1               | We will try again...

everything else seems to function and I can find no other errors...any suggestions?

**Comment by ffdixon** [comment]
You can't use https with an IP address.  You need to have a fully-qualified domain name, such as bbb.example.com with a valid certificate.

If you can use [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) to install BigBlueButton on a public server with a IP address, you can see what a valid setup looks like.

**Comment by rycaputo** [comment]
adding a fqdn is easy enough but still giving the
coturn_1               | ERROR: certificate doesn't exist yet.
coturn_1               | Certificate gets create on the first request to the HTTPS proxy.
coturn_1               | We will try again...

is it possible to turn off https:// in the configs or can you think of another reason the process is not working
