### ISSUE TITLE
400 Bad request when trying to start a room

### ISSUE THREAD

**Issue by rycaputo** [bigbluebutton/docker#288]
greenlight_1           | I, [2023-08-03T23:56:39.435508 #171]  INFO -- : [c7cf5a21-57de-4411-8fcb-f1ba699727dd] Completed 400 Bad Request in 21ms (Views: 0.5ms | ActiveRecord: 3.4ms | Allocations: 5879)
nginx_1                | 127.0.0.1 - - [03/Aug/2023:23:56:39 +0000] "POST /api/v1/meetings/xmr-x0k-os9-yl9/start.json HTTP/1.1" 400 23 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
https_proxy_1          | 69.104.55.214 - - [03/Aug/2023:23:56:39 +0000] "POST /api/v1/meetings/xmr-x0k-os9-yl9/start.json HTTP/2.0" 400 13 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

**Comment by rycaputo** [comment]
Is there any firewall rule which I need to apply or is it handles all by the docker install,  anyone have this issue where everything works up until the room session?

`bbb-mongodb            | {"t":{"$date":"2023-08-04T16:23:48.690+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1691166228:690160][1:0x7f5a89ad3700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 1652, snapshot max: 1652 snapshot count: 0, oldest timestamp: (1691166223, 1) , meta checkpoint timestamp: (1691166228, 1) base write gen: 23"}}
greenlight_1           | I, [2023-08-04T16:23:48.698923 #179]  INFO -- : [59169827-7b99-497d-a73d-0271c9ae69a2] Started GET "/api/v1/sessions.json" for 127.0.0.1 at 2023-08-04 16:23:48 +0000
greenlight_1           | I, [2023-08-04T16:23:48.700667 #179]  INFO -- : [59169827-7b99-497d-a73d-0271c9ae69a2] Processing by Api::V1::SessionsController#index as JSON
greenlight_1           | I, [2023-08-04T16:23:48.699746 #179]  INFO -- : [e92803f7-e9b2-4b29-8d09-d6b0ea21f282] Started GET "/api/v1/site_settings.json?names[]=PrimaryColor&names[]=PrimaryColorLight" for 127.0.0.1 at 2023-08-04 16:23:48 +0000
greenlight_1           | I, [2023-08-04T16:23:48.702675 #179]  INFO -- : [e92803f7-e9b2-4b29-8d09-d6b0ea21f282] Processing by Api::V1::SiteSettingsController#index as JSON
greenlight_1           | I, [2023-08-04T16:23:48.701111 #179]  INFO -- : [5ae3444c-afc7-4c7e-b5a8-8e9740f7df9c] Started GET "/api/v1/env.json" for 127.0.0.1 at 2023-08-04 16:23:48 +0000
greenlight_1           | I, [2023-08-04T16:23:48.703585 #179]  INFO -- : [5ae3444c-afc7-4c7e-b5a8-8e9740f7df9c] Processing by Api::V1::EnvController#index as JSON
greenlight_1           | I, [2023-08-04T16:23:48.704404 #179]  INFO -- : [5ae3444c-afc7-4c7e-b5a8-8e9740f7df9c] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.07ms)
greenlight_1           | I, [2023-08-04T16:23:48.704685 #179]  INFO -- : [5ae3444c-afc7-4c7e-b5a8-8e9740f7df9c] Completed 200 OK in 1ms (Views: 0.5ms | ActiveRecord: 0.0ms | Allocations: 218)
greenlight_1           | I, [2023-08-04T16:23:48.703798 #179]  INFO -- : [e92803f7-e9b2-4b29-8d09-d6b0ea21f282]   Parameters: {"names"=>["PrimaryColor", "PrimaryColorLight"]}
nginx_1                | 127.0.0.1 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/env.json HTTP/1.1" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
https_proxy_1          | 69.104.55.214 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/env.json HTTP/2.0" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
greenlight_1           | I, [2023-08-04T16:23:48.711435 #179]  INFO -- : [e92803f7-e9b2-4b29-8d09-d6b0ea21f282] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.08ms)
greenlight_1           | I, [2023-08-04T16:23:48.712468 #179]  INFO -- : [e92803f7-e9b2-4b29-8d09-d6b0ea21f282] Completed 200 OK in 7ms (Views: 1.3ms | ActiveRecord: 1.9ms | Allocations: 2327)
greenlight_1           | I, [2023-08-04T16:23:48.712281 #179]  INFO -- : [59169827-7b99-497d-a73d-0271c9ae69a2] [active_model_serializers] Rendered CurrentUserSerializer with ActiveModelSerializers::Adapter::Json (5.37ms)
nginx_1                | 127.0.0.1 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/site_settings.json?names[]=PrimaryColor&names[]=PrimaryColorLight HTTP/1.1" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
https_proxy_1          | 69.104.55.214 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/site_settings.json?names[]=PrimaryColor&names[]=PrimaryColorLight HTTP/2.0" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
greenlight_1           | I, [2023-08-04T16:23:48.713006 #179]  INFO -- : [59169827-7b99-497d-a73d-0271c9ae69a2] Completed 200 OK in 12ms (Views: 4.2ms | ActiveRecord: 2.8ms | Allocations: 4398)
https_proxy_1          | 69.104.55.214 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/sessions.json HTTP/2.0" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
nginx_1                | 127.0.0.1 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/sessions.json HTTP/1.1" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
greenlight_1           | I, [2023-08-04T16:23:48.734505 #179]  INFO -- : [cedf7e99-a936-4ae7-82fe-4aee5944eb02] Started GET "/api/v1/site_settings.json?names[]=Terms&names[]=PrivacyPolicy" for 127.0.0.1 at 2023-08-04 16:23:48 +0000
greenlight_1           | I, [2023-08-04T16:23:48.735308 #179]  INFO -- : [cedf7e99-a936-4ae7-82fe-4aee5944eb02] Processing by Api::V1::SiteSettingsController#index as JSON
greenlight_1           | I, [2023-08-04T16:23:48.735499 #179]  INFO -- : [cedf7e99-a936-4ae7-82fe-4aee5944eb02]   Parameters: {"names"=>["Terms", "PrivacyPolicy"]}
greenlight_1           | I, [2023-08-04T16:23:48.736583 #179]  INFO -- : [e8ca5d05-c8bf-4d05-896c-c1085b152d92] Started GET "/api/v1/rooms.json?search=" for 127.0.0.1 at 2023-08-04 16:23:48 +0000
greenlight_1           | I, [2023-08-04T16:23:48.737138 #179]  INFO -- : [e8ca5d05-c8bf-4d05-896c-c1085b152d92] Processing by Api::V1::RoomsController#index as JSON
greenlight_1           | I, [2023-08-04T16:23:48.737522 #179]  INFO -- : [e8ca5d05-c8bf-4d05-896c-c1085b152d92]   Parameters: {"search"=>""}
greenlight_1           | I, [2023-08-04T16:23:48.737808 #179]  INFO -- : [4d7b4b16-451c-4c74-9047-ec8599e33be7] Started GET "/api/v1/recordings/recordings_count.json" for 127.0.0.1 at 2023-08-04 16:23:48 +0000
greenlight_1           | I, [2023-08-04T16:23:48.738345 #179]  INFO -- : [4d7b4b16-451c-4c74-9047-ec8599e33be7] Processing by Api::V1::RecordingsController#recordings_count as JSON
greenlight_1           | I, [2023-08-04T16:23:48.738748 #179]  INFO -- : [c6d1a460-0f8c-412d-ba6a-14da4174d31e] Started GET "/api/v1/site_settings.json?names=BrandingImage" for 127.0.0.1 at 2023-08-04 16:23:48 +0000
greenlight_1           | I, [2023-08-04T16:23:48.741882 #179]  INFO -- : [c6d1a460-0f8c-412d-ba6a-14da4174d31e] Processing by Api::V1::SiteSettingsController#index as JSON
greenlight_1           | I, [2023-08-04T16:23:48.742113 #179]  INFO -- : [c6d1a460-0f8c-412d-ba6a-14da4174d31e]   Parameters: {"names"=>"BrandingImage"}
greenlight_1           | I, [2023-08-04T16:23:48.745330 #179]  INFO -- : [cedf7e99-a936-4ae7-82fe-4aee5944eb02] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.05ms)
greenlight_1           | I, [2023-08-04T16:23:48.746439 #179]  INFO -- : [cedf7e99-a936-4ae7-82fe-4aee5944eb02] Completed 200 OK in 10ms (Views: 1.3ms | ActiveRecord: 3.6ms | Allocations: 6844)
https_proxy_1          | 69.104.55.214 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/site_settings.json?names[]=Terms&names[]=PrivacyPolicy HTTP/2.0" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
nginx_1                | 127.0.0.1 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/site_settings.json?names[]=Terms&names[]=PrivacyPolicy HTTP/1.1" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
greenlight_1           | I, [2023-08-04T16:23:48.749092 #179]  INFO -- : [e8ca5d05-c8bf-4d05-896c-c1085b152d92] [active_model_serializers] Rendered ActiveModel::Serializer::CollectionSerializer with ActiveModelSerializers::Adapter::Json (0.25ms)
greenlight_1           | I, [2023-08-04T16:23:48.749555 #179]  INFO -- : [e8ca5d05-c8bf-4d05-896c-c1085b152d92] Completed 200 OK in 11ms (Views: 0.9ms | ActiveRecord: 4.8ms | Allocations: 6160)
nginx_1                | 127.0.0.1 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/rooms.json?search= HTTP/1.1" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
https_proxy_1          | 69.104.55.214 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/rooms.json?search= HTTP/2.0" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
greenlight_1           | I, [2023-08-04T16:23:48.760952 #179]  INFO -- : [c6d1a460-0f8c-412d-ba6a-14da4174d31e] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.04ms)
greenlight_1           | I, [2023-08-04T16:23:48.761098 #179]  INFO -- : [c6d1a460-0f8c-412d-ba6a-14da4174d31e] Completed 200 OK in 18ms (Views: 0.5ms | ActiveRecord: 9.1ms | Allocations: 8241)
nginx_1                | 127.0.0.1 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/site_settings.json?names=BrandingImage HTTP/1.1" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
https_proxy_1          | 69.104.55.214 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/site_settings.json?names=BrandingImage HTTP/2.0" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
greenlight_1           | I, [2023-08-04T16:23:48.765245 #179]  INFO -- : [4d7b4b16-451c-4c74-9047-ec8599e33be7] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.04ms)
greenlight_1           | I, [2023-08-04T16:23:48.765410 #179]  INFO -- : [4d7b4b16-451c-4c74-9047-ec8599e33be7] Completed 200 OK in 26ms (Views: 0.3ms | ActiveRecord: 10.4ms | Allocations: 11845)
nginx_1                | 127.0.0.1 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/recordings/recordings_count.json HTTP/1.1" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
https_proxy_1          | 69.104.55.214 - - [04/Aug/2023:16:23:48 +0000] "GET /api/v1/recordings/recordings_count.json HTTP/2.0" 304 0 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
greenlight_1           | I, [2023-08-04T16:23:48.781757 #179]  INFO -- : [67ff566b-7d46-4220-957b-3c142e003144] Started POST "/api/v1/meetings/ovz-wcl-a3g-3ct/start.json" for 127.0.0.1 at 2023-08-04 16:23:48 +0000
greenlight_1           | I, [2023-08-04T16:23:48.782577 #179]  INFO -- : [67ff566b-7d46-4220-957b-3c142e003144] Processing by Api::V1::MeetingsController#start as JSON
greenlight_1           | I, [2023-08-04T16:23:48.782620 #179]  INFO -- : [67ff566b-7d46-4220-957b-3c142e003144]   Parameters: {"friendly_id"=>"ovz-wcl-a3g-3ct"}
greenlight_1           | I, [2023-08-04T16:23:48.803102 #179]  INFO -- : [67ff566b-7d46-4220-957b-3c142e003144] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.04ms)
greenlight_1           | I, [2023-08-04T16:23:48.803420 #179]  INFO -- : [67ff566b-7d46-4220-957b-3c142e003144] Completed 400 Bad Request in 21ms (Views: 0.5ms | ActiveRecord: 3.9ms | Allocations: 5697)
nginx_1                | 127.0.0.1 - - [04/Aug/2023:16:23:48 +0000] "POST /api/v1/meetings/ovz-wcl-a3g-3ct/start.json HTTP/1.1" 400 23 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
https_proxy_1          | 69.104.55.214 - - [04/Aug/2023:16:23:48 +0000] "POST /api/v1/meetings/ovz-wcl-a3g-3ct/start.json HTTP/2.0" 400 13 "https://bbb.ole.foobar.com/rooms" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
`

**Comment by rycaputo** [comment]
I wonder if the null with hash is part of the problem?
` [6e89e41a-d261-4dd6-8282-08432a1bc5e2] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.06ms)
greenlight_1           | I, [2023-08-04T16:36:49.271589 #168]  INFO -- : [6e89e41a-d261-4dd6-8282-08432a1bc5e2] Completed 400 Bad Request in 17ms (Views: 0.4ms | ActiveRecord: 2.8ms | Allocations: 5213)
`

**Comment by rycaputo** [comment]
Holds on to old directories on reinstalls

**Comment by GiannisRallis** [comment]
Hello i have the same problem here how to remove the old directories? can you please inform me the solution here?
