### ISSUE TITLE
how to allow the https to use Mic and the Camera in several browsers

### ISSUE THREAD

**Issue by neutron92** [bigbluebutton/docker#3]
how to allow the https to use Mic and the Camera in several browsers

**Comment by neutron92** [comment]
![image](https://user-images.githubusercontent.com/6135555/38247640-4d1e78c8-3746-11e8-8d98-c54564f7c43d.png)

**Comment by neutron92** [comment]
![image](https://user-images.githubusercontent.com/6135555/38247654-59716284-3746-11e8-80a8-91b8f58e22cf.png)

**Comment by ffdixon** [comment]
The docker image is good for trying out a BigBlueButton server on a local machine, not for production.

If you want to setup a BigBlueButton server with HTTPS for use by many users, we make it easy to setup a server (with SSL + HTTPS) using bbb-install.sh. See https://github.com/bigbluebutton/bbb-install.

**Comment by ffdixon** [comment]
Are you trying to configure the docker image to use a hostname?  

Currently, the docker command only accepts an IP address for configuration.  We need to extend this to accept a server name, such as `-s bbb.my-server.com`.

**Comment by singhanju12340** [comment]
@ffdixon is it possible to try out the microphone and camera on docker image without installing SSL.
