### ISSUE TITLE
docker build -t bigbluebutton . fails

### ISSUE THREAD

**Issue by HappyMiner** [bigbluebutton/docker#32]
Hello,

In the past days I have tried to create a Docker image as described in [github.com/bigbluebutton/docker](https://github.com/bigbluebutton/docker
)
Unfortunately this fails completely and at several levels it seems (please see terminal output int the file attached). 

[BBB_install_errors.txt](https://github.com/bigbluebutton/docker/files/4146657/BBB_install_errors.txt)

I tried to login to the incomplete image via Docker and manually complete the failed parts. I believe I managed to complete the install through apt install bigbluebutton once, but then when I try: 
`docker run --rm -p 80:80/tcp -p 1935:1935 -p 3478:3478 -p 3478:3478/udp bbb -h 192.168.2.205`

I receive: 
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"-h\": executable file not found in $PATH": unknown.`

 **I am running Docker version:**
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**On MacOs Catalina:** 
`10.15.3`

**Additional insights I gathered during my trials:**

1. `/usr/local/lib/site_ruby/2.3.0/rubygems.rb:275:in 'find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /usr/local/bigbluebutton/core/Gemfile.lock. (Gem::GemNotFoundException)`

- [ ] Can be fixed through: 
- `cd /usr/local/bigbluebutton/core/ `
- Executing: `bundle update --bundler`
- Could there be an error in the script preventing an automated cd to the required directory?

2. When trying to continue the installation manually by reverse traversing the Docker file, I also encountered `Unable to locate package "bbb-etherpad"` when trying to install this package manually, hinting at a missing remote repository?
```
root@193314bd411d:/# apt-get install -y bbb-etherpad
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package bbb-etherpad
root@193314bd411d:/#
```

3. Since this missing package appears to be a game breaker, I decided to leave it at this. As a next step I might have tried to put the following in to a separate Docker file in order to have a chance of running this at all. Wondering if since this part was not reached in the Docker file, `docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"-h\": executable file not found in $PATH": unknown.` was thrown?
```
# -- Finish startup
ADD setup.sh /root/setup.sh
ENTRYPOINT ["/root/setup.sh"]
CMD []
```

4. For some reason the (partial) Docker image that was created only had an ID but no name. Anything missing in the initial command?

Please let me know if there is any solution to this. 
Many thanks in advance!

**Comment by ffdixon** [comment]
Got your message.  

We are planning to make some updates to the BigBlueButton docker container as it's not support SSL certificates for nginx (which are needed to enable the browser to send/receive audio and video through WebRTC).

We'll also remove the need to use port 1935 as that's for the older Flash component as well.

We'll be making these updates in the coming weeks, and we'll keep this ticket open until they are complete and the docker container is building again with the latest BigBlueButton 2.2.

**Comment by cyrilvimal** [comment]
Hi guys,

Got the same issue while building the image, did you get any clues to solve this?

**Comment by ffdixon** [comment]
Hi there,

The docker scripts need to be updated for BigBlueButton 2.2.  We've added the message o the top of the page that it's still work in progress.

Sorry for the inconvenience. We'll update this issue when the docker container is building again.

**Comment by L3o-pold** [comment]
Any update on this?

**Comment by Aoleara** [comment]
Delincuentes. Criminales

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
