### ISSUE TITLE
Session loads infinity

### ISSUE THREAD

**Issue by Nipotino2804** [bigbluebutton/docker#321]
Hello my BBB Session loads infinity. I can start a room, but i can't visit them. All Cotainers are running without problems.

**Comment by huy126123** [comment]
i have same problem :< . i can create room, but when join it's stuck at 3 dots forever.

**Comment by ben-ba** [comment]
disable your browser addons or start with an new blank profile;
for firefox
`about:profiles`
new profile -> launch additionally
had the same issue with firefox and addons.

**Comment by Nipotino2804** [comment]
I've reinstall bbb and reconfigurate the proxy and now everything works fine.
Thanks for your help
