### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by TuHuynhthanh** [bigbluebutton/docker#33]
[terminal.log](https://github.com/bigbluebutton/docker/files/4323222/terminal.log)
I got this error when i ran "docker built -t bigbluebutton .":

```
Errors were encountered while processing:
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get install -y bigbluebutton' returned a non-zero code: 100
```
Please show me how to fix this error. Thanks a lot.

**Comment by TuHuynhthanh** [comment]
this is my terminal log:
RubyGems installed the following executables:
        /usr/bin/gem2.3
        /usr/bin/bundle2.3

RubyGems system software updated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Fetching bundler-2.1.4.gem
Successfully installed bundler-2.1.4
1 gem installed
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Fetching builder-3.2.4.gem
Successfully installed builder-3.2.4
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Parsing documentation for builder-3.2.4
Installing ri documentation for builder-3.2.4
Done installing documentation for builder after 1 seconds
1 gem installed
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/local/lib/site_ruby/2.3.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /usr/local/bigbluebutton/core/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
        from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:294:in `activate_bin_path'
        from /usr/local/bin/bundle:23:in `<main>'
dpkg: error processing package bbb-record-core (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
Setting up libreoffice-pdfimport (1:5.1.6~rc2-0ubuntu1~xenial10) ...
Setting up humanity-icon-theme (0.6.10.1) ...
Setting up ubuntu-mono (14.04+16.04.20180326-0ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for systemd (229-4ubuntu21.27) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.32.2-1ubuntu1.6) ...
Processing triggers for dbus (1.10.6-1ubuntu3.5) ...
Processing triggers for dictionaries-common (1.26.3) ...
Errors were encountered while processing:
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get install -y bigbluebutton' returned a non-zero code: 100

**Comment by VincentSC** [comment]
Everybody probably has this. See #12 for a "fix"

**Comment by VincentSC** [comment]
Master branch has problems
> git checkout v2.2.x
> sudo docker build -t bigbluebutton .

**Comment by Inv0k-er** [comment]
And how to fix it ?

**Comment by dasJ** [comment]
As nobody from the bbb team seems to care about this, here is an ugly patch fixing your problem:

```diff
diff --git a/Dockerfile b/Dockerfile
index a8df291..5846900 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -31,7 +31,9 @@ RUN chmod +x /etc/init.d/tomcat7

 # -- Install BigBlueButton
 RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
-RUN apt-get install -y bigbluebutton
+RUN apt-get install -y bigbluebutton || :
+RUN gem install bundler -v 1.16.1
+RUN apt-get install -y bigbluebutton
 RUN apt-get install -y bbb-demo

 # -- Install mongodb (for HTML5 client)
```

**Comment by Aoleara** [comment]
Robo datos, manipulación, venta ilegal, tráfico de personas, violacion, amenazas de muerte. Etc Denuncia todos los nimbres

**Comment by Aoleara** [comment]
Estáis cometiendo delitos gravisimos

**Comment by VincentSC** [comment]
Translation: 
"_Data theft, manipulation, illegal sale, human trafficking, rape, death threats, etc. Denounce all names. You are committing serious crimes_"

Pretty sure this is not the right channel

**Comment by gcommit** [comment]
same error here. I tried the fix and it results in this: 

```
Reloading nginx using service
 * Reloading nginx configuration nginx
   ...fail!
dpkg: error processing package bbb-record-core (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-client; however:
  Package bbb-client is not configured yet.
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 bbb-client
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get install -y bigbluebutton' returned a non-zero code: 100
```

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
