### ISSUE TITLE
Add SSL setup to Install Instructions of BBB Docker

### ISSUE THREAD

**Issue by q2apro** [bigbluebutton/docker#339]
I used the BBB install instructions at https://github.com/bigbluebutton/docker/blob/develop/README.md

This worked. And the result was that I could open a running BBB instance at **http:**//myserveripaddress

Since modern browser require HTTP**S** this BBB instance cannot be used by my users.

I am not experienced with dockers and docker compose. 

IMHO, it is **essential** to add to the install tutorial, how to set up SSL with BBB docker. 

Please be so kind and add this information, or provide an additional instruction elsewhere. Thank you.

I am stuck and have no idea how to do this.

In best case, SSL would be supplied automatically when installing the docker. I have no idea if this is possible.

**Comment by yurikoles** [comment]
At the bottom of the root readme, there is a link to a doc that explains exactly what you ask: [How to integrate into an existing Web server setup](https://github.com/bigbluebutton/docker/blob/develop/docs/existing-web-server.md).

**Comment by q2apro** [comment]
I followed the instruction at https://github.com/bigbluebutton/docker/blob/develop/docs/existing-web-server.md#integration-with-nginx and added the code to `/etc/nginx/sites-available/bigblue.conf`, then linked the conf with `ln -s /etc/nginx/sites-available/bigblue.conf /etc/nginx/sites-enabled/`.

However, I still get:

![image](https://github.com/user-attachments/assets/cf8337be-078a-4992-a84b-1cdb7c31bf04)

Opening the IP directly, in "http" mode, I get:

![image](https://github.com/user-attachments/assets/c10407a1-6c7b-4a14-a12a-52a04362512f)
