### ISSUE TITLE
Build fails for latest HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/docker#4]
The Dockerfile needs to be updated to handle the recent updates to the HTML5 packages.  Reported in bigbluebutton-dev here

 https://groups.google.com/d/msg/bigbluebutton-dev/G8YJeTWNh6s/wSkc1WD5AQAJ

**Comment by kiransuthar** [comment]
Hi Fred, 
I am facing the same issue. Any updates on this ?

**Comment by kiransuthar** [comment]
Ok. Thanks for update.

**Comment by Aoleara** [comment]
> The Dockerfile needs to be updated to handle the recent updates to the HTML5 packages. Reported in bigbluebutton-dev here
> 
> https://groups.google.com/d/msg/bigbluebutton-dev/G8YJeTWNh6s/wSkc1WD5AQAJ

Gracias por las pruebas

**Comment by Aoleara** [comment]
Todo está registrado

**Comment by Aoleara** [comment]
Me dais asco

**Comment by Aoleara** [comment]
Venga seguid cobardes...  Of course en manada pq no os atrevéis solos. Pateticos

**Comment by Aoleara** [comment]
> Venga seguid cobardes... Of course en manada pq no os atrevéis solos. Pateticos

**Comment by valueerrorx** [comment]
so does this mean this docker image is working with the newest frontend now ? 
thx

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
