### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by DieProgrammIDE** [bigbluebutton/docker#47]
`To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:296:in `activate_bin_path'
from /usr/local/bin/bundle:23:in `<main>'
dpkg: error processing package bbb-record-core (--configure):
subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-playback-presentation; however:
Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
dependency problems - leaving unconfigured
Setting up libreoffice-pdfimport (1:5.1.6~rc2-0ubuntu1~xenial10) ...
Setting up humanity-icon-theme (0.6.10.1) ...
Setting up ubuntu-mono (14.04+16.04.20180326-0ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for systemd (229-4ubuntu21.28) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.32.2-1ubuntu1.6) ...
Processing triggers for dbus (1.10.6-1ubuntu3.5) ...
Processing triggers for dictionaries-common (1.26.3) ...
Errors were encountered while processing:
 bbb-record-core
 bbb-playback-presentation
 bbb-config
bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get install -y bigbluebutton' returned a non-zero code: 100 `

When trying to build on Ubuntu 18.04 Server, dpkg fails. Could somebody please provide an already built docker image?

**Comment by DieProgrammIDE** [comment]
Push!

**Comment by eugenetolok** [comment]
Push!

**Comment by Akshay-Hegde** [comment]
> Push!

No success with : https://hub.docker.com/r/bigbluebutton/bigbluebutton is 2 years and old its version 2, if someone have 2.2 docker would be nice to see.

Badly looking for 2.2 docker for testing.

**Comment by DieProgrammIDE** [comment]
Push!

**Comment by felbinger** [comment]
Still not working:
```
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/local/lib/site_ruby/2.3.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.16.1) required by your /usr/local/bigbluebutton/core/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.1`
	from /usr/local/lib/site_ruby/2.3.0/rubygems.rb:296:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
dpkg: error processing package bbb-record-core (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
Setting up libreoffice-pdfimport (1:5.1.6~rc2-0ubuntu1~xenial10) ...
Setting up humanity-icon-theme (0.6.10.1) ...
Setting up ubuntu-mono (14.04+16.04.20180326-0ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11.2) ...
Processing triggers for systemd (229-4ubuntu21.29) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.32.2-1ubuntu1.6) ...
Processing triggers for dbus (1.10.6-1ubuntu3.6) ...
Processing triggers for dictionaries-common (1.26.3) ...
Errors were encountered while processing:
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get install -y bigbluebutton' returned a non-zero code: 100
```

**Comment by alangecker** [comment]
@felbinger 
this docker repo is broken since a while, maybe rather try this fork?  :)
https://github.com/alangecker/bigbluebutton-docker

**Comment by felbinger** [comment]
Thanks, I'll check it out.

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
