### ISSUE TITLE
Branch: v2.2.x container creation fails

### ISSUE THREAD

**Issue by monochromec** [bigbluebutton/docker#48]
@tdjac0bs: container creation as described in the README-build.md fails 
as rc.local is trying to access  /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties which
doesn't exist yet as  BBB providing this directory is only installed if you run setup.sh in the container before the starting it up via systemd as outlined in the README-build.md.

I will try to issue a PR fixing this once I have a few spare cycles.

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
