### ISSUE TITLE
1002: Could not make a WebSocket connection

### ISSUE THREAD

**Issue by akashdk** [bigbluebutton/docker#49]
I successfully deployed the BBB container with the latest version. But unfortunately, I get `1002: Could not make a WebSocket connection`.
I try to debug the above error by enabling ports 
`docker run -d --name=$NAME --hostname=$HOSTNAME -p 16384:32768 -p 443:443 -p 80:80/tcp -p 1935:1935 -p 3478:3478/udp `
it doesn't work. All service is working properly I can't see any error in the logs.

I'm I missing something?.

thanks

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
