### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by k8smaster** [bigbluebutton/docker#53]
sed: can't read /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security: No such file or directory The command '/bin/sh -c sed -i 's|securerandom.source=file:/dev/random|securerandom.source=file:/dev/urandom|g'  /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security' returned a non-zero code: 2

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

How I can fix that issue?
Could you help please?

**Comment by alangecker** [comment]
@k8smaster 
I could not reproduce this error. Maybe there was something wrong which still gets cached?

maybe it gets fixed with a fresh rebuild:
```bash
$ ./scripts/compose build --no-cache core  
```

**Comment by alangecker** [comment]
@k8smaster 
ah sorry, I just realized, that I answered the question for the wrong repository... :sweat_smile: 

this repo here is quite outdated. but you could check out https://github.com/alangecker/bigbluebutton-docker

**Comment by citec** [comment]
Same build error here

**Comment by alangecker** [comment]
The code in this repository got basically replaced by a complete rewrite (see #43).
Most likely this issue no longer applies to the code.
I will close it for now, but feel free to reopen it if necessary! :)
