### ISSUE TITLE
greenlight error: 443/tcp connection refused

### ISSUE THREAD

**Issue by masterpi227** [bigbluebutton/docker#61]
production.log entry:

ERROR: [b733d7eb-0470-4ea1-bc8c-3d9652291329] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://$DOMAIN/bigbluebutton/api". Error: Failed to open TCP connection to v2202102130686141810.happysrv.de:443 (Connection refused - connect(2) for "$DOMAIN" port 443)

greenlight web UI:

"Serverfehler
BigBlueButton Endpunkt und Sicherheitsschlüssel ungültig"

api endpoint is reachable and respond SUCCESS. 

any ideas to debug?

**Comment by lonesomewalker** [comment]
v2202102130686141810.happysrv.de:443 is not reachable from outside.
Internal DNS resolving?

**Comment by masterpi227** [comment]
well, a http-request on 443 leads to the "bad request"
after restarting the container stack, greenlight did not throw the ERROR again. 
however, i did not change something at the nginx container or anything else regarding DNS resolving.
