### ISSUE TITLE
Replace Etherpad plugin

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/docker#67]
Hi @alangecker ,

Just a heads-up regarding a change I'm doing in one of the plugins we currently use. You will probably notice it in your update scripts but I'm adding here some extra context to it to spoil the surprise.

Since ep_delete_after_delay_lite (https://www.npmjs.com/package/ep_delete_after_delay_lite) is not working as expected anymore, and I believe it stopped working at the moment Etherpad started moving their `async` calls to `Promises`, I wrote a replacement ep_pad_ttl (https://github.com/pedrobmarin/ep_pad_ttl) to better fit our needs on removing Etherpad's data from Redis when pads stale. You can find some details on configuration at https://github.com/pedrobmarin/ep_pad_ttl#configuration and I'm available to answer any questions.

**Comment by alangecker** [comment]
hey @pedrobmarin 

big thanks for notifying! :)

It should hereby be done.
