### ISSUE TITLE
recordings not available

### ISSUE THREAD

**Issue by mokkin** [bigbluebutton/docker#71]
I just installed BBB through docker compose and everything seems to work except opening recordings. After the server has finished rendering, the recording appears

![grafik](https://user-images.githubusercontent.com/2938748/111043767-9eb16300-8444-11eb-901b-3b2453676674.png)

but after klicking on it I am redirected to a nginx error page:

![grafik](https://user-images.githubusercontent.com/2938748/111043772-a5d87100-8444-11eb-9606-7aaaab9d3858.png)

**Comment by alangecker** [comment]
@mokkin 
what is the URL/Link it leads you to?

there was a lot of work done recently on the bbb-playback feature with [v2.3-alpha-4](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-4). Most likely there is still something wrong in our nginx config / build here

**Comment by mokkin** [comment]
Sorry for the missing information. It is:

https://my.example.com/playback/presentation/2.3/05bbc51643d49e33e53baca2d2a9fb33dd803fad-1615651510102

**Comment by alangecker** [comment]
this should be fixed now! :)
try a `./scripts/upgrade` and `docker-compose up -d`
