### ISSUE TITLE
no screensharing possible

### ISSUE THREAD

**Issue by mokkin** [bigbluebutton/docker#75]
We tested the dockerized BBB today successfully with almost all functions. Unfortunately only screensharing didn't work, not in Firefox and not in Chrome. The presentator can select the screen, the clients receive the rotating errors to indicate, that the screensharing is starting, but the it ends with the message "screensharing stopped".
Both server and clients were Ubuntu 20.04.

**Comment by KingBBQ** [comment]
+1 having the same issue here. 
See attached log.

p.s. thanks for the great work - all the rest works so easy and great, so much easier to setup than the "normal" bbb
[log bbb docker screen sharing problems.log](https://github.com/bigbluebutton/docker/files/6244193/log.bbb.docker.screen.sharing.problems.log)

**Comment by alangecker** [comment]
Experienced the same, so I can confirm the issue, but haven't managed to look into it yet

**Comment by prlanzarin** [comment]
Which bbb-webrtc-sfu version is being pulled?

**Comment by prlanzarin** [comment]
https://github.com/bigbluebutton/docker/commit/96182bcc7469c336bb43e13ed477c94e4468987b

This looks like the last pull (correct me if I'm wrong).
If that is the last pull, then there's a configuration inconsistency:
`screensharePlayStartEnabled` should be `true` (but it's false by default in that pull). Current `master` branch [has it enabled by default](https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/80).
If you want to try that with a running container (to confirm that is the problem), there's an [environment variable for that](https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/master/config/custom-environment-variables.yml#L84). Pass `SCREENSHARE_PLAY_START_ENABLED=true` to the container.

**Comment by dsjiern** [comment]
> Pass `SCREENSHARE_PLAY_START_ENABLED=true` to the container.

Great! That resolves the problem! thanks very much!

**Comment by alangecker** [comment]
@prlanzarin 
aaah! thanks a lot! It would probably have taken me hours to debug it.
PR is on the way, but I couldn't test it yet. Will do it later in the evening.

I have seen `2.5.0-alpha.4` in the [`package.json`](https://github.com/alangecker/bbb-packages/commit/53e0eaa15a164b27c71d1315480b00e6a94c7da9) so I picked the commit with the name [`2.5.0-alpha.4`](https://github.com/bigbluebutton/bbb-webrtc-sfu/commit/78823ae5d673d8904145af7fa20130383a33b66f) without noticing, that it actually part of a merge.

For the v2.4.x releases you always set tags. It would be great for me if you could also tag the v2.5.x releases, so I would not have to guess with commit is included in the BBB 2.3 release :)

**Comment by prlanzarin** [comment]
Yeah. Mea culpa for not setting tags. I'm finishing up that branch and I should get back to tagging it soon.

**Comment by prlanzarin** [comment]
@alangecker just to let you know about the tagging: I've changed my mind. I just tagged the current master branch as [v2.5.0-alpha.4](https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.5.0-alpha.4) (and I'll keep tagging it). That new tag will land on beta2, and from beta2 onwards we can go to the old workflow of pulling from tags like v2.4.x was.

**Comment by KingBBQ** [comment]
wow, that was quick - just did an upgrade, and all works again - thanks a million!!!
