### ISSUE TITLE
error 1007 on remote side

### ISSUE THREAD

**Issue by damnms** [bigbluebutton/docker#80]
i have bbb working in my lan at 192.168.1.100, i registered a domain with dyndns and it seem to work, but when people try to use audio/video, they get an error 1007.
i checked that udp ports are forwarded correctly (16xxx up to 32xxx, dont know exactly the numbers) with nc and an echo test, that worked. 
i would assume with those ports open and forwarded anyone can connect but seems like (until now) no one except from inside my lan can connect with audio/video.
i can not set up a dedicated turn server which forwards all ports (1...65536) with tcp and udp because then i would lock my internet connection

**Comment by lonesomewalker** [comment]
then you should NOT run this at home...

**Comment by damnms** [comment]
congratz dude, you are one of the reasons i give up this software and instead switched to jitsi meet which... works like a charm out of the box.
