### ISSUE TITLE
where is the bbb-conf utility in the docker image?

### ISSUE THREAD

**Issue by mario-evangelista-silva** [bigbluebutton/docker#89]
where do I find the "bbb-conf" utility in the docker image to generate the BIGBLUEBUTTON_ENDPOINT and BIGBLUEBUTTON_SECRET credentials?

**Comment by dsjiern** [comment]
You can set the SECRET in the .env-file:
![grafik](https://user-images.githubusercontent.com/29799323/115989636-99a50f00-a5bf-11eb-9a6f-de954b3e93c9.png)

Endpoint-URL is https://<YOURDOMAIN>/bigbluebutton/

**Comment by alangecker** [comment]
basically a duplicate of #84

**Comment by ZelphirKaltstahl** [comment]
> You can set the SECRET in the .env-file: ![grafik](https://user-images.githubusercontent.com/29799323/115989636-99a50f00-a5bf-11eb-9a6f-de954b3e93c9.png)
> 
> Endpoint-URL is https:///bigbluebutton/

Surely you mean, that there is some domain between `https://` and `/bigbluebutton/`?
