### ISSUE TITLE
firewall on host to run bbb in docker 

### ISSUE THREAD

**Issue by martoni35** [bigbluebutton/docker#97]
Hello,

I docker bbb on a debian 10 and everything is good to have a good bbb service.
But when i want to securise the host firewall where docker is running, i have no sound and screen share....
In the host, i opened the follow ports : 80/tcp, 443/tcp, 16384-32768/udp, 3478, 1935, 7443 and 5066.
(informations with the official bbb documentation)

Is there someone to help to configure my FW ?

Bests,

martoni

**Comment by martoni35** [comment]
To complete, i git pull the code and i run bbb docker with the latest

**Comment by alangecker** [comment]
there were already quite some people with such issues. The most recent one #86.
I think it might be also, that your firewall settings also block the inter-container communication?
basically everything in `10.7.7.0/24` should also be allowed.

**Comment by doodlemania2** [comment]
This might be the resolution to my issue I just posted - but cannot do ufw allow 10.7.7.0/24 as it returns: Error: BAD PORT

**Comment by chfxr** [comment]
You are right, the command is not correct, it is: `sudo ufw allow from 10.7.7.0/24`

**Comment by martoni35** [comment]
Hello,
The solution is good....i didn't do the nice network configuration.... :(
Thx @chfxr :)
This issue is resolved and can be close
